//! Minecraft Java Edition wire protocol, generated from Mojang's own data.
//!
//! Since Minecraft 26.1 the server ships unobfuscated, so every name in this
//! crate is Mojang's own name and greps directly against the server jar.
//!
//! Three things come out of the jar and none of them is transcribed by hand:
//!
//! * `nix/extract-protocol.py` follows the server's own stream codecs down to
//!   the bytes and writes [`protocol.json`], which is committed beside this
//!   crate and regenerated by `nix run .#sync-minecraft-proto`.
//! * `build.rs` turns the layouts it recovered in full into the packet structs
//!   under [`packets`]. A layout the extractor could not follow all the way
//!   has no struct at all, so a generated codec is complete by construction.
//! * The version numbers, packet id tables and registries under [`generated`]
//!   are committed Rust, because they restate data rather than a wire contract
//!   and a reader wants to grep them.
//!
//! Packets the generator cannot produce are hand-written in the same modules,
//! against the same decompiled sources.
//!
//! [`protocol.json`]: https://github.com/andrewgazelka/hyperion/blob/main/crates/hyperion-minecraft-proto/protocol.json

// The derives emit `::hyperion_minecraft_proto` paths so that they work from
// any crate; this is what makes them resolve inside this one too.
extern crate self as hyperion_minecraft_proto;

pub mod block_state;
pub mod codec;
pub mod collision_shape;
pub mod framing;
pub mod generated;
pub mod item;
pub mod nbt;
pub mod packets;
pub mod particle;
pub mod registry_data;
pub mod tag_data;
pub mod text;
pub mod types;
pub mod world;

mod error;

pub use codec::{Reader, Writer};
pub use error::{Error, Result};
pub use generated::{MINECRAFT_VERSION, PROTOCOL_VERSION, WORLD_VERSION};
pub use hyperion_minecraft_proto_derive::{Decode, Encode};
pub use types::{
    BlockHitResult, BlockPos, ChunkPos, Direction, Either, Holder, Identifier, LengthPrefixed,
    RegistryId, Uuid, VarInt, VarLong,
};

/// A value that can be written to the wire.
pub trait Encode {
    /// Append the wire representation of `self` to `writer`.
    ///
    /// # Errors
    /// Returns an error when a value violates a protocol limit, such as a
    /// string longer than the field permits.
    fn encode(&self, writer: &mut Writer) -> Result<()>;
}

/// A value that can be read from the wire.
pub trait Decode<'a>: Sized {
    /// Read one value from `reader`, advancing it past the bytes consumed.
    ///
    /// # Errors
    /// Returns an error on truncated input or a malformed encoding.
    fn decode(reader: &mut Reader<'a>) -> Result<Self>;
}
