// @generated by nix/generate-particles.py from Minecraft 26.2 (protocol 776).
// Do not edit by hand. Regenerate with: nix run .#sync-minecraft-particles

//! Particle types for Minecraft 26.2, and the options each one carries.
//!
//! `ParticleTypes.STREAM_CODEC` is `ByteBufCodecs.registry(PARTICLE_TYPE)
//! .dispatch(ParticleOptions::getType, ParticleType::streamCodec)`: a `VarInt`
//! id, then whatever that id's own codec writes. [`Particle`] is that pair as
//! one closed value, so a caller cannot name a type and forget its body.
//!
//! There is no `Particle::from_id`. A type id alone does not say how many
//! bytes follow it, so turning one back into a particle means reading the
//! body, which is [`Particle::decode`]. [`ParticleKind`] is the id on its own,
//! for the cases that really do only want the number or the name.
//!
//! Both enums are closed and neither has an `Unknown` variant. A type this
//! server never sends is also a type whose body length it does not know, and
//! nothing after the particle is length-prefixed, so there is nothing to skip
//! past: the read has to stop rather than resynchronise on the next field.
//!
//! # Why this registry is generated apart from the others
//!
//! The general registry codegen emits one id-only enum per registry out of
//! `protocol.json`, and it deliberately skips `minecraft:particle_type`. That
//! file cannot express this one: the extractor marks
//! `ParticleTypes#STREAM_CODEC` `unresolved`, because following a dispatch
//! needs the runtime type, so all it carries for particles is the names.
//! `nix/generate-particles.py` reads the dispatch table out of the decompiled
//! Java instead, which is the only place that says which of the 125 entries
//! carry a payload and what shape it is.
//!
//! **Do not re-add `minecraft:particle_type` to the general codegen.** Two
//! spellings of one registry can drift, and a drifted particle id draws the
//! wrong particle rather than failing. What makes the split safe is
//! `particle_ids_match_the_registry` below, which holds every id here against
//! `generated::registry::PARTICLE_TYPE`.

use crate::{
    Decode, Encode, Error, Reader, Result, Writer,
    item::{ItemStackTemplate, nbt::NbtScan},
    types::{BlockPos, BlockStateId, Vec3},
};

/// A packed ARGB colour, as a particle option carries it.
///
/// Vanilla writes this through the same `ByteBufCodecs.INT` it writes a count
/// with, so only the field name distinguishes the two in the Java. Giving it a
/// type here is what stops a caller passing a particle count where a colour
/// goes, which is a mistake only a client ever sees.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Argb(i32);

impl Argb {
    /// A colour from its four channels.
    #[must_use]
    pub const fn new(alpha: u8, red: u8, green: u8, blue: u8) -> Self {
        Self(((alpha as i32) << 24) | ((red as i32) << 16) | ((green as i32) << 8) | (blue as i32))
    }

    /// A fully opaque colour.
    #[must_use]
    pub const fn opaque(red: u8, green: u8, blue: u8) -> Self {
        Self::new(0xff, red, green, blue)
    }

    /// The packed value exactly as the wire holds it.
    #[must_use]
    pub const fn from_bits(bits: i32) -> Self {
        Self(bits)
    }

    /// The packed value exactly as the wire holds it.
    #[must_use]
    pub const fn to_bits(self) -> i32 {
        self.0
    }

    /// Alpha, red, green, blue.
    ///
    /// Big-endian bytes rather than shifts: the wire writes this `int` big
    /// endian, so the byte order already is the channel order.
    #[must_use]
    pub const fn channels(self) -> [u8; 4] {
        self.0.to_be_bytes()
    }
}

/// Where a vibration is travelling to (`PositionSource`).
///
/// Another registry dispatch, over `minecraft:position_source_type`, which has exactly
/// the two entries below. A third would land here as a build failure in
/// `nix/generate-particles.py` rather than as a wrong body on the wire.
#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(u16)]
pub enum PositionSource {
    /// `minecraft:block` (`BlockPositionSource`).
    Block {
        /// `BlockPositionSource.pos`.
        pos: BlockPos,
    } = 0,
    /// `minecraft:entity` (`EntityPositionSource`).
    Entity {
        /// `EntityPositionSource.id`.
        id: i32,
        /// `EntityPositionSource.y_offset`.
        y_offset: f32,
    } = 1,
}

impl PositionSource {
    /// The `minecraft:position_source_type` id this variant is dispatched on.
    #[must_use]
    pub const fn id(&self) -> u16 {
        match self {
            Self::Block { .. } => 0,
            Self::Entity { .. } => 1,
        }
    }
}

impl Encode for PositionSource {
    fn encode(&self, writer: &mut Writer) -> Result<()> {
        writer.var_int(i32::from(self.id()));
        match self {
            Self::Block { pos } => {
                pos.encode(writer)?;
            }
            Self::Entity { id, y_offset } => {
                writer.var_int(*id);
                writer.f32(*y_offset);
            }
        }
        Ok(())
    }
}

impl Decode<'_> for PositionSource {
    fn decode(reader: &mut Reader<'_>) -> Result<Self> {
        let id = reader.var_int()?;
        match id {
            0 => Ok(Self::Block {
                pos: BlockPos::decode(reader)?,
            }),
            1 => Ok(Self::Entity {
                id: reader.var_int()?,
                y_offset: reader.f32()?,
            }),
            value => Err(Error::InvalidEnum {
                name: "PositionSource",
                value,
            }),
        }
    }
}

/// A particle type, without its options.
///
/// The discriminant is the `minecraft:particle_type` id, so [`id`](Self::id)
/// is a move rather than a table lookup. Registry ids are positional and shift
/// whenever Mojang inserts a type, which is why they are generated rather than
/// written down.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum ParticleKind {
    /// `minecraft:angry_villager`.
    AngryVillager = 0,
    /// `minecraft:block`.
    Block = 1,
    /// `minecraft:block_marker`.
    BlockMarker = 2,
    /// `minecraft:bubble`.
    Bubble = 3,
    /// `minecraft:sulfur_bubbles`.
    SulfurBubbles = 4,
    /// `minecraft:noxious_gas`.
    NoxiousGas = 5,
    /// `minecraft:noxious_gas_cloud`.
    NoxiousGasCloud = 6,
    /// `minecraft:geyser`.
    Geyser = 7,
    /// `minecraft:geyser_base`.
    GeyserBase = 8,
    /// `minecraft:geyser_poof`.
    GeyserPoof = 9,
    /// `minecraft:geyser_plume`.
    GeyserPlume = 10,
    /// `minecraft:cloud`.
    Cloud = 11,
    /// `minecraft:copper_fire_flame`.
    CopperFireFlame = 12,
    /// `minecraft:crit`.
    Crit = 13,
    /// `minecraft:damage_indicator`.
    DamageIndicator = 14,
    /// `minecraft:dragon_breath`.
    DragonBreath = 15,
    /// `minecraft:dripping_lava`.
    DrippingLava = 16,
    /// `minecraft:falling_lava`.
    FallingLava = 17,
    /// `minecraft:landing_lava`.
    LandingLava = 18,
    /// `minecraft:dripping_water`.
    DrippingWater = 19,
    /// `minecraft:falling_water`.
    FallingWater = 20,
    /// `minecraft:dust`.
    Dust = 21,
    /// `minecraft:dust_color_transition`.
    DustColorTransition = 22,
    /// `minecraft:effect`.
    Effect = 23,
    /// `minecraft:elder_guardian`.
    ElderGuardian = 24,
    /// `minecraft:enchanted_hit`.
    EnchantedHit = 25,
    /// `minecraft:enchant`.
    Enchant = 26,
    /// `minecraft:end_rod`.
    EndRod = 27,
    /// `minecraft:entity_effect`.
    EntityEffect = 28,
    /// `minecraft:explosion_emitter`.
    ExplosionEmitter = 29,
    /// `minecraft:explosion`.
    Explosion = 30,
    /// `minecraft:gust`.
    Gust = 31,
    /// `minecraft:small_gust`.
    SmallGust = 32,
    /// `minecraft:gust_emitter_large`.
    GustEmitterLarge = 33,
    /// `minecraft:gust_emitter_small`.
    GustEmitterSmall = 34,
    /// `minecraft:sonic_boom`.
    SonicBoom = 35,
    /// `minecraft:falling_dust`.
    FallingDust = 36,
    /// `minecraft:firework`.
    Firework = 37,
    /// `minecraft:fishing`.
    Fishing = 38,
    /// `minecraft:flame`.
    Flame = 39,
    /// `minecraft:infested`.
    Infested = 40,
    /// `minecraft:cherry_leaves`.
    CherryLeaves = 41,
    /// `minecraft:pale_oak_leaves`.
    PaleOakLeaves = 42,
    /// `minecraft:tinted_leaves`.
    TintedLeaves = 43,
    /// `minecraft:sculk_soul`.
    SculkSoul = 44,
    /// `minecraft:sculk_charge`.
    SculkCharge = 45,
    /// `minecraft:sculk_charge_pop`.
    SculkChargePop = 46,
    /// `minecraft:soul_fire_flame`.
    SoulFireFlame = 47,
    /// `minecraft:soul`.
    Soul = 48,
    /// `minecraft:flash`.
    Flash = 49,
    /// `minecraft:happy_villager`.
    HappyVillager = 50,
    /// `minecraft:composter`.
    Composter = 51,
    /// `minecraft:heart`.
    Heart = 52,
    /// `minecraft:instant_effect`.
    InstantEffect = 53,
    /// `minecraft:item`.
    Item = 54,
    /// `minecraft:vibration`.
    Vibration = 55,
    /// `minecraft:trail`.
    Trail = 56,
    /// `minecraft:pause_mob_growth`.
    PauseMobGrowth = 57,
    /// `minecraft:reset_mob_growth`.
    ResetMobGrowth = 58,
    /// `minecraft:item_slime`.
    ItemSlime = 59,
    /// `minecraft:item_cobweb`.
    ItemCobweb = 60,
    /// `minecraft:item_snowball`.
    ItemSnowball = 61,
    /// `minecraft:large_smoke`.
    LargeSmoke = 62,
    /// `minecraft:lava`.
    Lava = 63,
    /// `minecraft:mycelium`.
    Mycelium = 64,
    /// `minecraft:note`.
    Note = 65,
    /// `minecraft:poof`.
    Poof = 66,
    /// `minecraft:portal`.
    Portal = 67,
    /// `minecraft:rain`.
    Rain = 68,
    /// `minecraft:smoke`.
    Smoke = 69,
    /// `minecraft:white_smoke`.
    WhiteSmoke = 70,
    /// `minecraft:sneeze`.
    Sneeze = 71,
    /// `minecraft:spit`.
    Spit = 72,
    /// `minecraft:squid_ink`.
    SquidInk = 73,
    /// `minecraft:sweep_attack`.
    SweepAttack = 74,
    /// `minecraft:totem_of_undying`.
    TotemOfUndying = 75,
    /// `minecraft:underwater`.
    Underwater = 76,
    /// `minecraft:splash`.
    Splash = 77,
    /// `minecraft:witch`.
    Witch = 78,
    /// `minecraft:bubble_pop`.
    BubblePop = 79,
    /// `minecraft:current_down`.
    CurrentDown = 80,
    /// `minecraft:bubble_column_up`.
    BubbleColumnUp = 81,
    /// `minecraft:nautilus`.
    Nautilus = 82,
    /// `minecraft:dolphin`.
    Dolphin = 83,
    /// `minecraft:campfire_cosy_smoke`.
    CampfireCosySmoke = 84,
    /// `minecraft:campfire_signal_smoke`.
    CampfireSignalSmoke = 85,
    /// `minecraft:dripping_honey`.
    DrippingHoney = 86,
    /// `minecraft:falling_honey`.
    FallingHoney = 87,
    /// `minecraft:landing_honey`.
    LandingHoney = 88,
    /// `minecraft:falling_nectar`.
    FallingNectar = 89,
    /// `minecraft:falling_spore_blossom`.
    FallingSporeBlossom = 90,
    /// `minecraft:ash`.
    Ash = 91,
    /// `minecraft:crimson_spore`.
    CrimsonSpore = 92,
    /// `minecraft:warped_spore`.
    WarpedSpore = 93,
    /// `minecraft:spore_blossom_air`.
    SporeBlossomAir = 94,
    /// `minecraft:dripping_obsidian_tear`.
    DrippingObsidianTear = 95,
    /// `minecraft:falling_obsidian_tear`.
    FallingObsidianTear = 96,
    /// `minecraft:landing_obsidian_tear`.
    LandingObsidianTear = 97,
    /// `minecraft:reverse_portal`.
    ReversePortal = 98,
    /// `minecraft:white_ash`.
    WhiteAsh = 99,
    /// `minecraft:small_flame`.
    SmallFlame = 100,
    /// `minecraft:snowflake`.
    Snowflake = 101,
    /// `minecraft:dripping_dripstone_lava`.
    DrippingDripstoneLava = 102,
    /// `minecraft:falling_dripstone_lava`.
    FallingDripstoneLava = 103,
    /// `minecraft:dripping_dripstone_water`.
    DrippingDripstoneWater = 104,
    /// `minecraft:falling_dripstone_water`.
    FallingDripstoneWater = 105,
    /// `minecraft:glow_squid_ink`.
    GlowSquidInk = 106,
    /// `minecraft:glow`.
    Glow = 107,
    /// `minecraft:wax_on`.
    WaxOn = 108,
    /// `minecraft:wax_off`.
    WaxOff = 109,
    /// `minecraft:electric_spark`.
    ElectricSpark = 110,
    /// `minecraft:scrape`.
    Scrape = 111,
    /// `minecraft:shriek`.
    Shriek = 112,
    /// `minecraft:egg_crack`.
    EggCrack = 113,
    /// `minecraft:dust_plume`.
    DustPlume = 114,
    /// `minecraft:trial_spawner_detection`.
    TrialSpawnerDetection = 115,
    /// `minecraft:trial_spawner_detection_ominous`.
    TrialSpawnerDetectionOminous = 116,
    /// `minecraft:vault_connection`.
    VaultConnection = 117,
    /// `minecraft:dust_pillar`.
    DustPillar = 118,
    /// `minecraft:ominous_spawning`.
    OminousSpawning = 119,
    /// `minecraft:raid_omen`.
    RaidOmen = 120,
    /// `minecraft:trial_omen`.
    TrialOmen = 121,
    /// `minecraft:block_crumble`.
    BlockCrumble = 122,
    /// `minecraft:firefly`.
    Firefly = 123,
    /// `minecraft:sulfur_cube_goo`.
    SulfurCubeGoo = 124,
}

impl ParticleKind {
    /// Every type, in id order, so the index is the id.
    pub const ALL: &'static [Self] = &[
        Self::AngryVillager,
        Self::Block,
        Self::BlockMarker,
        Self::Bubble,
        Self::SulfurBubbles,
        Self::NoxiousGas,
        Self::NoxiousGasCloud,
        Self::Geyser,
        Self::GeyserBase,
        Self::GeyserPoof,
        Self::GeyserPlume,
        Self::Cloud,
        Self::CopperFireFlame,
        Self::Crit,
        Self::DamageIndicator,
        Self::DragonBreath,
        Self::DrippingLava,
        Self::FallingLava,
        Self::LandingLava,
        Self::DrippingWater,
        Self::FallingWater,
        Self::Dust,
        Self::DustColorTransition,
        Self::Effect,
        Self::ElderGuardian,
        Self::EnchantedHit,
        Self::Enchant,
        Self::EndRod,
        Self::EntityEffect,
        Self::ExplosionEmitter,
        Self::Explosion,
        Self::Gust,
        Self::SmallGust,
        Self::GustEmitterLarge,
        Self::GustEmitterSmall,
        Self::SonicBoom,
        Self::FallingDust,
        Self::Firework,
        Self::Fishing,
        Self::Flame,
        Self::Infested,
        Self::CherryLeaves,
        Self::PaleOakLeaves,
        Self::TintedLeaves,
        Self::SculkSoul,
        Self::SculkCharge,
        Self::SculkChargePop,
        Self::SoulFireFlame,
        Self::Soul,
        Self::Flash,
        Self::HappyVillager,
        Self::Composter,
        Self::Heart,
        Self::InstantEffect,
        Self::Item,
        Self::Vibration,
        Self::Trail,
        Self::PauseMobGrowth,
        Self::ResetMobGrowth,
        Self::ItemSlime,
        Self::ItemCobweb,
        Self::ItemSnowball,
        Self::LargeSmoke,
        Self::Lava,
        Self::Mycelium,
        Self::Note,
        Self::Poof,
        Self::Portal,
        Self::Rain,
        Self::Smoke,
        Self::WhiteSmoke,
        Self::Sneeze,
        Self::Spit,
        Self::SquidInk,
        Self::SweepAttack,
        Self::TotemOfUndying,
        Self::Underwater,
        Self::Splash,
        Self::Witch,
        Self::BubblePop,
        Self::CurrentDown,
        Self::BubbleColumnUp,
        Self::Nautilus,
        Self::Dolphin,
        Self::CampfireCosySmoke,
        Self::CampfireSignalSmoke,
        Self::DrippingHoney,
        Self::FallingHoney,
        Self::LandingHoney,
        Self::FallingNectar,
        Self::FallingSporeBlossom,
        Self::Ash,
        Self::CrimsonSpore,
        Self::WarpedSpore,
        Self::SporeBlossomAir,
        Self::DrippingObsidianTear,
        Self::FallingObsidianTear,
        Self::LandingObsidianTear,
        Self::ReversePortal,
        Self::WhiteAsh,
        Self::SmallFlame,
        Self::Snowflake,
        Self::DrippingDripstoneLava,
        Self::FallingDripstoneLava,
        Self::DrippingDripstoneWater,
        Self::FallingDripstoneWater,
        Self::GlowSquidInk,
        Self::Glow,
        Self::WaxOn,
        Self::WaxOff,
        Self::ElectricSpark,
        Self::Scrape,
        Self::Shriek,
        Self::EggCrack,
        Self::DustPlume,
        Self::TrialSpawnerDetection,
        Self::TrialSpawnerDetectionOminous,
        Self::VaultConnection,
        Self::DustPillar,
        Self::OminousSpawning,
        Self::RaidOmen,
        Self::TrialOmen,
        Self::BlockCrumble,
        Self::Firefly,
        Self::SulfurCubeGoo,
    ];

    /// The `minecraft:particle_type` id.
    #[must_use]
    pub const fn id(self) -> u16 {
        self as u16
    }

    /// The namespaced registry name, e.g. `minecraft:flame`.
    #[must_use]
    pub const fn name(self) -> &'static str {
        PARTICLE_NAMES[self as usize]
    }

    /// The type an id off the wire names, if this version has one.
    ///
    /// The decode boundary and nowhere else: a type named in source goes
    /// through the variant, so a version that drops it fails to build.
    #[must_use]
    pub const fn from_id(id: u16) -> Option<Self> {
        match id {
            0 => Some(Self::AngryVillager),
            1 => Some(Self::Block),
            2 => Some(Self::BlockMarker),
            3 => Some(Self::Bubble),
            4 => Some(Self::SulfurBubbles),
            5 => Some(Self::NoxiousGas),
            6 => Some(Self::NoxiousGasCloud),
            7 => Some(Self::Geyser),
            8 => Some(Self::GeyserBase),
            9 => Some(Self::GeyserPoof),
            10 => Some(Self::GeyserPlume),
            11 => Some(Self::Cloud),
            12 => Some(Self::CopperFireFlame),
            13 => Some(Self::Crit),
            14 => Some(Self::DamageIndicator),
            15 => Some(Self::DragonBreath),
            16 => Some(Self::DrippingLava),
            17 => Some(Self::FallingLava),
            18 => Some(Self::LandingLava),
            19 => Some(Self::DrippingWater),
            20 => Some(Self::FallingWater),
            21 => Some(Self::Dust),
            22 => Some(Self::DustColorTransition),
            23 => Some(Self::Effect),
            24 => Some(Self::ElderGuardian),
            25 => Some(Self::EnchantedHit),
            26 => Some(Self::Enchant),
            27 => Some(Self::EndRod),
            28 => Some(Self::EntityEffect),
            29 => Some(Self::ExplosionEmitter),
            30 => Some(Self::Explosion),
            31 => Some(Self::Gust),
            32 => Some(Self::SmallGust),
            33 => Some(Self::GustEmitterLarge),
            34 => Some(Self::GustEmitterSmall),
            35 => Some(Self::SonicBoom),
            36 => Some(Self::FallingDust),
            37 => Some(Self::Firework),
            38 => Some(Self::Fishing),
            39 => Some(Self::Flame),
            40 => Some(Self::Infested),
            41 => Some(Self::CherryLeaves),
            42 => Some(Self::PaleOakLeaves),
            43 => Some(Self::TintedLeaves),
            44 => Some(Self::SculkSoul),
            45 => Some(Self::SculkCharge),
            46 => Some(Self::SculkChargePop),
            47 => Some(Self::SoulFireFlame),
            48 => Some(Self::Soul),
            49 => Some(Self::Flash),
            50 => Some(Self::HappyVillager),
            51 => Some(Self::Composter),
            52 => Some(Self::Heart),
            53 => Some(Self::InstantEffect),
            54 => Some(Self::Item),
            55 => Some(Self::Vibration),
            56 => Some(Self::Trail),
            57 => Some(Self::PauseMobGrowth),
            58 => Some(Self::ResetMobGrowth),
            59 => Some(Self::ItemSlime),
            60 => Some(Self::ItemCobweb),
            61 => Some(Self::ItemSnowball),
            62 => Some(Self::LargeSmoke),
            63 => Some(Self::Lava),
            64 => Some(Self::Mycelium),
            65 => Some(Self::Note),
            66 => Some(Self::Poof),
            67 => Some(Self::Portal),
            68 => Some(Self::Rain),
            69 => Some(Self::Smoke),
            70 => Some(Self::WhiteSmoke),
            71 => Some(Self::Sneeze),
            72 => Some(Self::Spit),
            73 => Some(Self::SquidInk),
            74 => Some(Self::SweepAttack),
            75 => Some(Self::TotemOfUndying),
            76 => Some(Self::Underwater),
            77 => Some(Self::Splash),
            78 => Some(Self::Witch),
            79 => Some(Self::BubblePop),
            80 => Some(Self::CurrentDown),
            81 => Some(Self::BubbleColumnUp),
            82 => Some(Self::Nautilus),
            83 => Some(Self::Dolphin),
            84 => Some(Self::CampfireCosySmoke),
            85 => Some(Self::CampfireSignalSmoke),
            86 => Some(Self::DrippingHoney),
            87 => Some(Self::FallingHoney),
            88 => Some(Self::LandingHoney),
            89 => Some(Self::FallingNectar),
            90 => Some(Self::FallingSporeBlossom),
            91 => Some(Self::Ash),
            92 => Some(Self::CrimsonSpore),
            93 => Some(Self::WarpedSpore),
            94 => Some(Self::SporeBlossomAir),
            95 => Some(Self::DrippingObsidianTear),
            96 => Some(Self::FallingObsidianTear),
            97 => Some(Self::LandingObsidianTear),
            98 => Some(Self::ReversePortal),
            99 => Some(Self::WhiteAsh),
            100 => Some(Self::SmallFlame),
            101 => Some(Self::Snowflake),
            102 => Some(Self::DrippingDripstoneLava),
            103 => Some(Self::FallingDripstoneLava),
            104 => Some(Self::DrippingDripstoneWater),
            105 => Some(Self::FallingDripstoneWater),
            106 => Some(Self::GlowSquidInk),
            107 => Some(Self::Glow),
            108 => Some(Self::WaxOn),
            109 => Some(Self::WaxOff),
            110 => Some(Self::ElectricSpark),
            111 => Some(Self::Scrape),
            112 => Some(Self::Shriek),
            113 => Some(Self::EggCrack),
            114 => Some(Self::DustPlume),
            115 => Some(Self::TrialSpawnerDetection),
            116 => Some(Self::TrialSpawnerDetectionOminous),
            117 => Some(Self::VaultConnection),
            118 => Some(Self::DustPillar),
            119 => Some(Self::OminousSpawning),
            120 => Some(Self::RaidOmen),
            121 => Some(Self::TrialOmen),
            122 => Some(Self::BlockCrumble),
            123 => Some(Self::Firefly),
            124 => Some(Self::SulfurCubeGoo),
            _ => None,
        }
    }

    /// The type of that namespaced name, if this version has one.
    #[must_use]
    pub fn from_name(name: &str) -> Option<Self> {
        // A scan rather than a map: the table is small and this runs when a
        // name arrives from outside, not per tick.
        let index = PARTICLE_NAMES.iter().position(|entry| *entry == name)?;
        Self::from_id(u16::try_from(index).ok()?)
    }
}

/// Every registry name, in id order.
static PARTICLE_NAMES: [&str; 125] = [
    "minecraft:angry_villager",
    "minecraft:block",
    "minecraft:block_marker",
    "minecraft:bubble",
    "minecraft:sulfur_bubbles",
    "minecraft:noxious_gas",
    "minecraft:noxious_gas_cloud",
    "minecraft:geyser",
    "minecraft:geyser_base",
    "minecraft:geyser_poof",
    "minecraft:geyser_plume",
    "minecraft:cloud",
    "minecraft:copper_fire_flame",
    "minecraft:crit",
    "minecraft:damage_indicator",
    "minecraft:dragon_breath",
    "minecraft:dripping_lava",
    "minecraft:falling_lava",
    "minecraft:landing_lava",
    "minecraft:dripping_water",
    "minecraft:falling_water",
    "minecraft:dust",
    "minecraft:dust_color_transition",
    "minecraft:effect",
    "minecraft:elder_guardian",
    "minecraft:enchanted_hit",
    "minecraft:enchant",
    "minecraft:end_rod",
    "minecraft:entity_effect",
    "minecraft:explosion_emitter",
    "minecraft:explosion",
    "minecraft:gust",
    "minecraft:small_gust",
    "minecraft:gust_emitter_large",
    "minecraft:gust_emitter_small",
    "minecraft:sonic_boom",
    "minecraft:falling_dust",
    "minecraft:firework",
    "minecraft:fishing",
    "minecraft:flame",
    "minecraft:infested",
    "minecraft:cherry_leaves",
    "minecraft:pale_oak_leaves",
    "minecraft:tinted_leaves",
    "minecraft:sculk_soul",
    "minecraft:sculk_charge",
    "minecraft:sculk_charge_pop",
    "minecraft:soul_fire_flame",
    "minecraft:soul",
    "minecraft:flash",
    "minecraft:happy_villager",
    "minecraft:composter",
    "minecraft:heart",
    "minecraft:instant_effect",
    "minecraft:item",
    "minecraft:vibration",
    "minecraft:trail",
    "minecraft:pause_mob_growth",
    "minecraft:reset_mob_growth",
    "minecraft:item_slime",
    "minecraft:item_cobweb",
    "minecraft:item_snowball",
    "minecraft:large_smoke",
    "minecraft:lava",
    "minecraft:mycelium",
    "minecraft:note",
    "minecraft:poof",
    "minecraft:portal",
    "minecraft:rain",
    "minecraft:smoke",
    "minecraft:white_smoke",
    "minecraft:sneeze",
    "minecraft:spit",
    "minecraft:squid_ink",
    "minecraft:sweep_attack",
    "minecraft:totem_of_undying",
    "minecraft:underwater",
    "minecraft:splash",
    "minecraft:witch",
    "minecraft:bubble_pop",
    "minecraft:current_down",
    "minecraft:bubble_column_up",
    "minecraft:nautilus",
    "minecraft:dolphin",
    "minecraft:campfire_cosy_smoke",
    "minecraft:campfire_signal_smoke",
    "minecraft:dripping_honey",
    "minecraft:falling_honey",
    "minecraft:landing_honey",
    "minecraft:falling_nectar",
    "minecraft:falling_spore_blossom",
    "minecraft:ash",
    "minecraft:crimson_spore",
    "minecraft:warped_spore",
    "minecraft:spore_blossom_air",
    "minecraft:dripping_obsidian_tear",
    "minecraft:falling_obsidian_tear",
    "minecraft:landing_obsidian_tear",
    "minecraft:reverse_portal",
    "minecraft:white_ash",
    "minecraft:small_flame",
    "minecraft:snowflake",
    "minecraft:dripping_dripstone_lava",
    "minecraft:falling_dripstone_lava",
    "minecraft:dripping_dripstone_water",
    "minecraft:falling_dripstone_water",
    "minecraft:glow_squid_ink",
    "minecraft:glow",
    "minecraft:wax_on",
    "minecraft:wax_off",
    "minecraft:electric_spark",
    "minecraft:scrape",
    "minecraft:shriek",
    "minecraft:egg_crack",
    "minecraft:dust_plume",
    "minecraft:trial_spawner_detection",
    "minecraft:trial_spawner_detection_ominous",
    "minecraft:vault_connection",
    "minecraft:dust_pillar",
    "minecraft:ominous_spawning",
    "minecraft:raid_omen",
    "minecraft:trial_omen",
    "minecraft:block_crumble",
    "minecraft:firefly",
    "minecraft:sulfur_cube_goo",
];

/// A particle type together with the options its own codec writes.
///
/// One value rather than a type beside a body, because the two are not
/// independent: the id decides how many bytes follow, and nothing after them
/// is length-prefixed. A `Dust` sent without its colour and scale does not
/// draw a colourless dust, it desynchronises the rest of the frame.
#[derive(Debug, Clone, PartialEq)]
#[repr(u16)]
pub enum Particle<'a> {
    /// `minecraft:angry_villager`, no options.
    AngryVillager = 0,
    /// `minecraft:block`, a `BlockParticleOption`.
    Block {
        /// `BlockParticleOption.state`.
        state: BlockStateId,
    } = 1,
    /// `minecraft:block_marker`, a `BlockParticleOption`.
    BlockMarker {
        /// `BlockParticleOption.state`.
        state: BlockStateId,
    } = 2,
    /// `minecraft:bubble`, no options.
    Bubble = 3,
    /// `minecraft:sulfur_bubbles`, no options.
    SulfurBubbles = 4,
    /// `minecraft:noxious_gas`, no options.
    NoxiousGas = 5,
    /// `minecraft:noxious_gas_cloud`, no options.
    NoxiousGasCloud = 6,
    /// `minecraft:geyser`, a `GeyserParticleOptions`.
    Geyser {
        /// `GeyserParticleOptions.water_blocks`.
        water_blocks: i32,
    } = 7,
    /// `minecraft:geyser_base`, a `GeyserBaseParticleOptions`.
    GeyserBase {
        /// `GeyserBaseParticleOptions.water_blocks`.
        water_blocks: i32,
        /// `GeyserBaseParticleOptions.burst_impulse_base`.
        burst_impulse_base: f32,
    } = 8,
    /// `minecraft:geyser_poof`, a `GeyserBaseParticleOptions`.
    GeyserPoof {
        /// `GeyserBaseParticleOptions.water_blocks`.
        water_blocks: i32,
        /// `GeyserBaseParticleOptions.burst_impulse_base`.
        burst_impulse_base: f32,
    } = 9,
    /// `minecraft:geyser_plume`, a `GeyserParticleOptions`.
    GeyserPlume {
        /// `GeyserParticleOptions.water_blocks`.
        water_blocks: i32,
    } = 10,
    /// `minecraft:cloud`, no options.
    Cloud = 11,
    /// `minecraft:copper_fire_flame`, no options.
    CopperFireFlame = 12,
    /// `minecraft:crit`, no options.
    Crit = 13,
    /// `minecraft:damage_indicator`, no options.
    DamageIndicator = 14,
    /// `minecraft:dragon_breath`, a `PowerParticleOption`.
    DragonBreath {
        /// `PowerParticleOption.power`.
        power: f32,
    } = 15,
    /// `minecraft:dripping_lava`, no options.
    DrippingLava = 16,
    /// `minecraft:falling_lava`, no options.
    FallingLava = 17,
    /// `minecraft:landing_lava`, no options.
    LandingLava = 18,
    /// `minecraft:dripping_water`, no options.
    DrippingWater = 19,
    /// `minecraft:falling_water`, no options.
    FallingWater = 20,
    /// `minecraft:dust`, a `DustParticleOptions`.
    Dust {
        /// `DustParticleOptions.color`.
        color: Argb,
        /// `DustParticleOptions.scale`.
        scale: f32,
    } = 21,
    /// `minecraft:dust_color_transition`, a `DustColorTransitionOptions`.
    DustColorTransition {
        /// `DustColorTransitionOptions.from_color`.
        from_color: Argb,
        /// `DustColorTransitionOptions.to_color`.
        to_color: Argb,
        /// `DustColorTransitionOptions.scale`.
        scale: f32,
    } = 22,
    /// `minecraft:effect`, a `SpellParticleOption`.
    Effect {
        /// `SpellParticleOption.color`.
        color: Argb,
        /// `SpellParticleOption.power`.
        power: f32,
    } = 23,
    /// `minecraft:elder_guardian`, no options.
    ElderGuardian = 24,
    /// `minecraft:enchanted_hit`, no options.
    EnchantedHit = 25,
    /// `minecraft:enchant`, no options.
    Enchant = 26,
    /// `minecraft:end_rod`, no options.
    EndRod = 27,
    /// `minecraft:entity_effect`, a `ColorParticleOption`.
    EntityEffect {
        /// `ColorParticleOption.color`.
        color: Argb,
    } = 28,
    /// `minecraft:explosion_emitter`, no options.
    ExplosionEmitter = 29,
    /// `minecraft:explosion`, no options.
    Explosion = 30,
    /// `minecraft:gust`, no options.
    Gust = 31,
    /// `minecraft:small_gust`, no options.
    SmallGust = 32,
    /// `minecraft:gust_emitter_large`, no options.
    GustEmitterLarge = 33,
    /// `minecraft:gust_emitter_small`, no options.
    GustEmitterSmall = 34,
    /// `minecraft:sonic_boom`, no options.
    SonicBoom = 35,
    /// `minecraft:falling_dust`, a `BlockParticleOption`.
    FallingDust {
        /// `BlockParticleOption.state`.
        state: BlockStateId,
    } = 36,
    /// `minecraft:firework`, no options.
    Firework = 37,
    /// `minecraft:fishing`, no options.
    Fishing = 38,
    /// `minecraft:flame`, no options.
    Flame = 39,
    /// `minecraft:infested`, no options.
    Infested = 40,
    /// `minecraft:cherry_leaves`, no options.
    CherryLeaves = 41,
    /// `minecraft:pale_oak_leaves`, no options.
    PaleOakLeaves = 42,
    /// `minecraft:tinted_leaves`, a `ColorParticleOption`.
    TintedLeaves {
        /// `ColorParticleOption.color`.
        color: Argb,
    } = 43,
    /// `minecraft:sculk_soul`, no options.
    SculkSoul = 44,
    /// `minecraft:sculk_charge`, a `SculkChargeParticleOptions`.
    SculkCharge {
        /// `SculkChargeParticleOptions.roll`.
        roll: f32,
    } = 45,
    /// `minecraft:sculk_charge_pop`, no options.
    SculkChargePop = 46,
    /// `minecraft:soul_fire_flame`, no options.
    SoulFireFlame = 47,
    /// `minecraft:soul`, no options.
    Soul = 48,
    /// `minecraft:flash`, a `ColorParticleOption`.
    Flash {
        /// `ColorParticleOption.color`.
        color: Argb,
    } = 49,
    /// `minecraft:happy_villager`, no options.
    HappyVillager = 50,
    /// `minecraft:composter`, no options.
    Composter = 51,
    /// `minecraft:heart`, no options.
    Heart = 52,
    /// `minecraft:instant_effect`, a `SpellParticleOption`.
    InstantEffect {
        /// `SpellParticleOption.color`.
        color: Argb,
        /// `SpellParticleOption.power`.
        power: f32,
    } = 53,
    /// `minecraft:item`, a `ItemParticleOption`.
    Item {
        /// `ItemParticleOption.item_stack`.
        item_stack: ItemStackTemplate<'a>,
    } = 54,
    /// `minecraft:vibration`, a `VibrationParticleOption`.
    Vibration {
        /// `VibrationParticleOption.destination`.
        destination: PositionSource,
        /// `VibrationParticleOption.arrival_in_ticks`.
        arrival_in_ticks: i32,
    } = 55,
    /// `minecraft:trail`, a `TrailParticleOption`.
    Trail {
        /// `TrailParticleOption.target`.
        target: Vec3,
        /// `TrailParticleOption.color`.
        color: Argb,
        /// `TrailParticleOption.duration`.
        duration: i32,
    } = 56,
    /// `minecraft:pause_mob_growth`, no options.
    PauseMobGrowth = 57,
    /// `minecraft:reset_mob_growth`, no options.
    ResetMobGrowth = 58,
    /// `minecraft:item_slime`, no options.
    ItemSlime = 59,
    /// `minecraft:item_cobweb`, no options.
    ItemCobweb = 60,
    /// `minecraft:item_snowball`, no options.
    ItemSnowball = 61,
    /// `minecraft:large_smoke`, no options.
    LargeSmoke = 62,
    /// `minecraft:lava`, no options.
    Lava = 63,
    /// `minecraft:mycelium`, no options.
    Mycelium = 64,
    /// `minecraft:note`, no options.
    Note = 65,
    /// `minecraft:poof`, no options.
    Poof = 66,
    /// `minecraft:portal`, no options.
    Portal = 67,
    /// `minecraft:rain`, no options.
    Rain = 68,
    /// `minecraft:smoke`, no options.
    Smoke = 69,
    /// `minecraft:white_smoke`, no options.
    WhiteSmoke = 70,
    /// `minecraft:sneeze`, no options.
    Sneeze = 71,
    /// `minecraft:spit`, no options.
    Spit = 72,
    /// `minecraft:squid_ink`, no options.
    SquidInk = 73,
    /// `minecraft:sweep_attack`, no options.
    SweepAttack = 74,
    /// `minecraft:totem_of_undying`, no options.
    TotemOfUndying = 75,
    /// `minecraft:underwater`, no options.
    Underwater = 76,
    /// `minecraft:splash`, no options.
    Splash = 77,
    /// `minecraft:witch`, no options.
    Witch = 78,
    /// `minecraft:bubble_pop`, no options.
    BubblePop = 79,
    /// `minecraft:current_down`, no options.
    CurrentDown = 80,
    /// `minecraft:bubble_column_up`, no options.
    BubbleColumnUp = 81,
    /// `minecraft:nautilus`, no options.
    Nautilus = 82,
    /// `minecraft:dolphin`, no options.
    Dolphin = 83,
    /// `minecraft:campfire_cosy_smoke`, no options.
    CampfireCosySmoke = 84,
    /// `minecraft:campfire_signal_smoke`, no options.
    CampfireSignalSmoke = 85,
    /// `minecraft:dripping_honey`, no options.
    DrippingHoney = 86,
    /// `minecraft:falling_honey`, no options.
    FallingHoney = 87,
    /// `minecraft:landing_honey`, no options.
    LandingHoney = 88,
    /// `minecraft:falling_nectar`, no options.
    FallingNectar = 89,
    /// `minecraft:falling_spore_blossom`, no options.
    FallingSporeBlossom = 90,
    /// `minecraft:ash`, no options.
    Ash = 91,
    /// `minecraft:crimson_spore`, no options.
    CrimsonSpore = 92,
    /// `minecraft:warped_spore`, no options.
    WarpedSpore = 93,
    /// `minecraft:spore_blossom_air`, no options.
    SporeBlossomAir = 94,
    /// `minecraft:dripping_obsidian_tear`, no options.
    DrippingObsidianTear = 95,
    /// `minecraft:falling_obsidian_tear`, no options.
    FallingObsidianTear = 96,
    /// `minecraft:landing_obsidian_tear`, no options.
    LandingObsidianTear = 97,
    /// `minecraft:reverse_portal`, no options.
    ReversePortal = 98,
    /// `minecraft:white_ash`, no options.
    WhiteAsh = 99,
    /// `minecraft:small_flame`, no options.
    SmallFlame = 100,
    /// `minecraft:snowflake`, no options.
    Snowflake = 101,
    /// `minecraft:dripping_dripstone_lava`, no options.
    DrippingDripstoneLava = 102,
    /// `minecraft:falling_dripstone_lava`, no options.
    FallingDripstoneLava = 103,
    /// `minecraft:dripping_dripstone_water`, no options.
    DrippingDripstoneWater = 104,
    /// `minecraft:falling_dripstone_water`, no options.
    FallingDripstoneWater = 105,
    /// `minecraft:glow_squid_ink`, no options.
    GlowSquidInk = 106,
    /// `minecraft:glow`, no options.
    Glow = 107,
    /// `minecraft:wax_on`, no options.
    WaxOn = 108,
    /// `minecraft:wax_off`, no options.
    WaxOff = 109,
    /// `minecraft:electric_spark`, no options.
    ElectricSpark = 110,
    /// `minecraft:scrape`, no options.
    Scrape = 111,
    /// `minecraft:shriek`, a `ShriekParticleOption`.
    Shriek {
        /// `ShriekParticleOption.delay`.
        delay: i32,
    } = 112,
    /// `minecraft:egg_crack`, no options.
    EggCrack = 113,
    /// `minecraft:dust_plume`, no options.
    DustPlume = 114,
    /// `minecraft:trial_spawner_detection`, no options.
    TrialSpawnerDetection = 115,
    /// `minecraft:trial_spawner_detection_ominous`, no options.
    TrialSpawnerDetectionOminous = 116,
    /// `minecraft:vault_connection`, no options.
    VaultConnection = 117,
    /// `minecraft:dust_pillar`, a `BlockParticleOption`.
    DustPillar {
        /// `BlockParticleOption.state`.
        state: BlockStateId,
    } = 118,
    /// `minecraft:ominous_spawning`, no options.
    OminousSpawning = 119,
    /// `minecraft:raid_omen`, no options.
    RaidOmen = 120,
    /// `minecraft:trial_omen`, no options.
    TrialOmen = 121,
    /// `minecraft:block_crumble`, a `BlockParticleOption`.
    BlockCrumble {
        /// `BlockParticleOption.state`.
        state: BlockStateId,
    } = 122,
    /// `minecraft:firefly`, no options.
    Firefly = 123,
    /// `minecraft:sulfur_cube_goo`, no options.
    SulfurCubeGoo = 124,
}

impl Particle<'_> {
    /// The type, without its options.
    #[must_use]
    pub const fn kind(&self) -> ParticleKind {
        match self {
            Self::AngryVillager => ParticleKind::AngryVillager,
            Self::Block { .. } => ParticleKind::Block,
            Self::BlockMarker { .. } => ParticleKind::BlockMarker,
            Self::Bubble => ParticleKind::Bubble,
            Self::SulfurBubbles => ParticleKind::SulfurBubbles,
            Self::NoxiousGas => ParticleKind::NoxiousGas,
            Self::NoxiousGasCloud => ParticleKind::NoxiousGasCloud,
            Self::Geyser { .. } => ParticleKind::Geyser,
            Self::GeyserBase { .. } => ParticleKind::GeyserBase,
            Self::GeyserPoof { .. } => ParticleKind::GeyserPoof,
            Self::GeyserPlume { .. } => ParticleKind::GeyserPlume,
            Self::Cloud => ParticleKind::Cloud,
            Self::CopperFireFlame => ParticleKind::CopperFireFlame,
            Self::Crit => ParticleKind::Crit,
            Self::DamageIndicator => ParticleKind::DamageIndicator,
            Self::DragonBreath { .. } => ParticleKind::DragonBreath,
            Self::DrippingLava => ParticleKind::DrippingLava,
            Self::FallingLava => ParticleKind::FallingLava,
            Self::LandingLava => ParticleKind::LandingLava,
            Self::DrippingWater => ParticleKind::DrippingWater,
            Self::FallingWater => ParticleKind::FallingWater,
            Self::Dust { .. } => ParticleKind::Dust,
            Self::DustColorTransition { .. } => ParticleKind::DustColorTransition,
            Self::Effect { .. } => ParticleKind::Effect,
            Self::ElderGuardian => ParticleKind::ElderGuardian,
            Self::EnchantedHit => ParticleKind::EnchantedHit,
            Self::Enchant => ParticleKind::Enchant,
            Self::EndRod => ParticleKind::EndRod,
            Self::EntityEffect { .. } => ParticleKind::EntityEffect,
            Self::ExplosionEmitter => ParticleKind::ExplosionEmitter,
            Self::Explosion => ParticleKind::Explosion,
            Self::Gust => ParticleKind::Gust,
            Self::SmallGust => ParticleKind::SmallGust,
            Self::GustEmitterLarge => ParticleKind::GustEmitterLarge,
            Self::GustEmitterSmall => ParticleKind::GustEmitterSmall,
            Self::SonicBoom => ParticleKind::SonicBoom,
            Self::FallingDust { .. } => ParticleKind::FallingDust,
            Self::Firework => ParticleKind::Firework,
            Self::Fishing => ParticleKind::Fishing,
            Self::Flame => ParticleKind::Flame,
            Self::Infested => ParticleKind::Infested,
            Self::CherryLeaves => ParticleKind::CherryLeaves,
            Self::PaleOakLeaves => ParticleKind::PaleOakLeaves,
            Self::TintedLeaves { .. } => ParticleKind::TintedLeaves,
            Self::SculkSoul => ParticleKind::SculkSoul,
            Self::SculkCharge { .. } => ParticleKind::SculkCharge,
            Self::SculkChargePop => ParticleKind::SculkChargePop,
            Self::SoulFireFlame => ParticleKind::SoulFireFlame,
            Self::Soul => ParticleKind::Soul,
            Self::Flash { .. } => ParticleKind::Flash,
            Self::HappyVillager => ParticleKind::HappyVillager,
            Self::Composter => ParticleKind::Composter,
            Self::Heart => ParticleKind::Heart,
            Self::InstantEffect { .. } => ParticleKind::InstantEffect,
            Self::Item { .. } => ParticleKind::Item,
            Self::Vibration { .. } => ParticleKind::Vibration,
            Self::Trail { .. } => ParticleKind::Trail,
            Self::PauseMobGrowth => ParticleKind::PauseMobGrowth,
            Self::ResetMobGrowth => ParticleKind::ResetMobGrowth,
            Self::ItemSlime => ParticleKind::ItemSlime,
            Self::ItemCobweb => ParticleKind::ItemCobweb,
            Self::ItemSnowball => ParticleKind::ItemSnowball,
            Self::LargeSmoke => ParticleKind::LargeSmoke,
            Self::Lava => ParticleKind::Lava,
            Self::Mycelium => ParticleKind::Mycelium,
            Self::Note => ParticleKind::Note,
            Self::Poof => ParticleKind::Poof,
            Self::Portal => ParticleKind::Portal,
            Self::Rain => ParticleKind::Rain,
            Self::Smoke => ParticleKind::Smoke,
            Self::WhiteSmoke => ParticleKind::WhiteSmoke,
            Self::Sneeze => ParticleKind::Sneeze,
            Self::Spit => ParticleKind::Spit,
            Self::SquidInk => ParticleKind::SquidInk,
            Self::SweepAttack => ParticleKind::SweepAttack,
            Self::TotemOfUndying => ParticleKind::TotemOfUndying,
            Self::Underwater => ParticleKind::Underwater,
            Self::Splash => ParticleKind::Splash,
            Self::Witch => ParticleKind::Witch,
            Self::BubblePop => ParticleKind::BubblePop,
            Self::CurrentDown => ParticleKind::CurrentDown,
            Self::BubbleColumnUp => ParticleKind::BubbleColumnUp,
            Self::Nautilus => ParticleKind::Nautilus,
            Self::Dolphin => ParticleKind::Dolphin,
            Self::CampfireCosySmoke => ParticleKind::CampfireCosySmoke,
            Self::CampfireSignalSmoke => ParticleKind::CampfireSignalSmoke,
            Self::DrippingHoney => ParticleKind::DrippingHoney,
            Self::FallingHoney => ParticleKind::FallingHoney,
            Self::LandingHoney => ParticleKind::LandingHoney,
            Self::FallingNectar => ParticleKind::FallingNectar,
            Self::FallingSporeBlossom => ParticleKind::FallingSporeBlossom,
            Self::Ash => ParticleKind::Ash,
            Self::CrimsonSpore => ParticleKind::CrimsonSpore,
            Self::WarpedSpore => ParticleKind::WarpedSpore,
            Self::SporeBlossomAir => ParticleKind::SporeBlossomAir,
            Self::DrippingObsidianTear => ParticleKind::DrippingObsidianTear,
            Self::FallingObsidianTear => ParticleKind::FallingObsidianTear,
            Self::LandingObsidianTear => ParticleKind::LandingObsidianTear,
            Self::ReversePortal => ParticleKind::ReversePortal,
            Self::WhiteAsh => ParticleKind::WhiteAsh,
            Self::SmallFlame => ParticleKind::SmallFlame,
            Self::Snowflake => ParticleKind::Snowflake,
            Self::DrippingDripstoneLava => ParticleKind::DrippingDripstoneLava,
            Self::FallingDripstoneLava => ParticleKind::FallingDripstoneLava,
            Self::DrippingDripstoneWater => ParticleKind::DrippingDripstoneWater,
            Self::FallingDripstoneWater => ParticleKind::FallingDripstoneWater,
            Self::GlowSquidInk => ParticleKind::GlowSquidInk,
            Self::Glow => ParticleKind::Glow,
            Self::WaxOn => ParticleKind::WaxOn,
            Self::WaxOff => ParticleKind::WaxOff,
            Self::ElectricSpark => ParticleKind::ElectricSpark,
            Self::Scrape => ParticleKind::Scrape,
            Self::Shriek { .. } => ParticleKind::Shriek,
            Self::EggCrack => ParticleKind::EggCrack,
            Self::DustPlume => ParticleKind::DustPlume,
            Self::TrialSpawnerDetection => ParticleKind::TrialSpawnerDetection,
            Self::TrialSpawnerDetectionOminous => ParticleKind::TrialSpawnerDetectionOminous,
            Self::VaultConnection => ParticleKind::VaultConnection,
            Self::DustPillar { .. } => ParticleKind::DustPillar,
            Self::OminousSpawning => ParticleKind::OminousSpawning,
            Self::RaidOmen => ParticleKind::RaidOmen,
            Self::TrialOmen => ParticleKind::TrialOmen,
            Self::BlockCrumble { .. } => ParticleKind::BlockCrumble,
            Self::Firefly => ParticleKind::Firefly,
            Self::SulfurCubeGoo => ParticleKind::SulfurCubeGoo,
        }
    }

    /// The `minecraft:particle_type` id.
    #[must_use]
    pub const fn id(&self) -> u16 {
        self.kind().id()
    }

    /// The namespaced registry name, e.g. `minecraft:flame`.
    #[must_use]
    pub const fn name(&self) -> &'static str {
        self.kind().name()
    }
}

impl Encode for Particle<'_> {
    fn encode(&self, writer: &mut Writer) -> Result<()> {
        writer.var_int(i32::from(self.id()));
        match self {
            Self::AngryVillager
            | Self::Bubble
            | Self::SulfurBubbles
            | Self::NoxiousGas
            | Self::NoxiousGasCloud
            | Self::Cloud
            | Self::CopperFireFlame
            | Self::Crit
            | Self::DamageIndicator
            | Self::DrippingLava
            | Self::FallingLava
            | Self::LandingLava
            | Self::DrippingWater
            | Self::FallingWater
            | Self::ElderGuardian
            | Self::EnchantedHit
            | Self::Enchant
            | Self::EndRod
            | Self::ExplosionEmitter
            | Self::Explosion
            | Self::Gust
            | Self::SmallGust
            | Self::GustEmitterLarge
            | Self::GustEmitterSmall
            | Self::SonicBoom
            | Self::Firework
            | Self::Fishing
            | Self::Flame
            | Self::Infested
            | Self::CherryLeaves
            | Self::PaleOakLeaves
            | Self::SculkSoul
            | Self::SculkChargePop
            | Self::SoulFireFlame
            | Self::Soul
            | Self::HappyVillager
            | Self::Composter
            | Self::Heart
            | Self::PauseMobGrowth
            | Self::ResetMobGrowth
            | Self::ItemSlime
            | Self::ItemCobweb
            | Self::ItemSnowball
            | Self::LargeSmoke
            | Self::Lava
            | Self::Mycelium
            | Self::Note
            | Self::Poof
            | Self::Portal
            | Self::Rain
            | Self::Smoke
            | Self::WhiteSmoke
            | Self::Sneeze
            | Self::Spit
            | Self::SquidInk
            | Self::SweepAttack
            | Self::TotemOfUndying
            | Self::Underwater
            | Self::Splash
            | Self::Witch
            | Self::BubblePop
            | Self::CurrentDown
            | Self::BubbleColumnUp
            | Self::Nautilus
            | Self::Dolphin
            | Self::CampfireCosySmoke
            | Self::CampfireSignalSmoke
            | Self::DrippingHoney
            | Self::FallingHoney
            | Self::LandingHoney
            | Self::FallingNectar
            | Self::FallingSporeBlossom
            | Self::Ash
            | Self::CrimsonSpore
            | Self::WarpedSpore
            | Self::SporeBlossomAir
            | Self::DrippingObsidianTear
            | Self::FallingObsidianTear
            | Self::LandingObsidianTear
            | Self::ReversePortal
            | Self::WhiteAsh
            | Self::SmallFlame
            | Self::Snowflake
            | Self::DrippingDripstoneLava
            | Self::FallingDripstoneLava
            | Self::DrippingDripstoneWater
            | Self::FallingDripstoneWater
            | Self::GlowSquidInk
            | Self::Glow
            | Self::WaxOn
            | Self::WaxOff
            | Self::ElectricSpark
            | Self::Scrape
            | Self::EggCrack
            | Self::DustPlume
            | Self::TrialSpawnerDetection
            | Self::TrialSpawnerDetectionOminous
            | Self::VaultConnection
            | Self::OminousSpawning
            | Self::RaidOmen
            | Self::TrialOmen
            | Self::Firefly
            | Self::SulfurCubeGoo => {}
            Self::Block { state }
            | Self::BlockMarker { state }
            | Self::FallingDust { state }
            | Self::DustPillar { state }
            | Self::BlockCrumble { state } => {
                writer.var_int(state.to_raw());
            }
            Self::Geyser { water_blocks } | Self::GeyserPlume { water_blocks } => {
                writer.i32(*water_blocks);
            }
            Self::GeyserBase {
                water_blocks,
                burst_impulse_base,
            }
            | Self::GeyserPoof {
                water_blocks,
                burst_impulse_base,
            } => {
                writer.i32(*water_blocks);
                writer.f32(*burst_impulse_base);
            }
            Self::DragonBreath { power } => {
                writer.f32(*power);
            }
            Self::Dust { color, scale } => {
                writer.i32(color.to_bits());
                writer.f32(*scale);
            }
            Self::DustColorTransition {
                from_color,
                to_color,
                scale,
            } => {
                writer.i32(from_color.to_bits());
                writer.i32(to_color.to_bits());
                writer.f32(*scale);
            }
            Self::Effect { color, power } | Self::InstantEffect { color, power } => {
                writer.i32(color.to_bits());
                writer.f32(*power);
            }
            Self::EntityEffect { color } | Self::TintedLeaves { color } | Self::Flash { color } => {
                writer.i32(color.to_bits());
            }
            Self::SculkCharge { roll } => {
                writer.f32(*roll);
            }
            Self::Item { item_stack } => {
                item_stack.encode(writer)?;
            }
            Self::Vibration {
                destination,
                arrival_in_ticks,
            } => {
                destination.encode(writer)?;
                writer.var_int(*arrival_in_ticks);
            }
            Self::Trail {
                target,
                color,
                duration,
            } => {
                target.encode(writer)?;
                writer.i32(color.to_bits());
                writer.var_int(*duration);
            }
            Self::Shriek { delay } => {
                writer.var_int(*delay);
            }
        }
        Ok(())
    }
}

impl<'a> Particle<'a> {
    /// Read a particle and whatever its type's codec wrote after the id.
    ///
    /// Not a [`Decode`] impl, because one variant carries an item stack and a
    /// stack's component values can only be measured with an NBT scanner. Same
    /// shape as [`crate::packets::play::SetEquipment::decode`], for the same
    /// reason.
    ///
    /// # Errors
    /// [`Error::InvalidEnum`] for a type this version does not have. There is
    /// no recovery from that: the id is what says how long the body is, so an
    /// unknown one leaves nothing to skip.
    pub fn decode(reader: &mut Reader<'a>, nbt: &impl NbtScan) -> Result<Self> {
        let id = reader.var_int()?;
        match id {
            0 => Ok(Self::AngryVillager),
            1 => Ok(Self::Block {
                state: BlockStateId::from_raw(reader.var_int()?)?,
            }),
            2 => Ok(Self::BlockMarker {
                state: BlockStateId::from_raw(reader.var_int()?)?,
            }),
            3 => Ok(Self::Bubble),
            4 => Ok(Self::SulfurBubbles),
            5 => Ok(Self::NoxiousGas),
            6 => Ok(Self::NoxiousGasCloud),
            7 => Ok(Self::Geyser {
                water_blocks: reader.i32()?,
            }),
            8 => Ok(Self::GeyserBase {
                water_blocks: reader.i32()?,
                burst_impulse_base: reader.f32()?,
            }),
            9 => Ok(Self::GeyserPoof {
                water_blocks: reader.i32()?,
                burst_impulse_base: reader.f32()?,
            }),
            10 => Ok(Self::GeyserPlume {
                water_blocks: reader.i32()?,
            }),
            11 => Ok(Self::Cloud),
            12 => Ok(Self::CopperFireFlame),
            13 => Ok(Self::Crit),
            14 => Ok(Self::DamageIndicator),
            15 => Ok(Self::DragonBreath {
                power: reader.f32()?,
            }),
            16 => Ok(Self::DrippingLava),
            17 => Ok(Self::FallingLava),
            18 => Ok(Self::LandingLava),
            19 => Ok(Self::DrippingWater),
            20 => Ok(Self::FallingWater),
            21 => Ok(Self::Dust {
                color: Argb::from_bits(reader.i32()?),
                scale: reader.f32()?,
            }),
            22 => Ok(Self::DustColorTransition {
                from_color: Argb::from_bits(reader.i32()?),
                to_color: Argb::from_bits(reader.i32()?),
                scale: reader.f32()?,
            }),
            23 => Ok(Self::Effect {
                color: Argb::from_bits(reader.i32()?),
                power: reader.f32()?,
            }),
            24 => Ok(Self::ElderGuardian),
            25 => Ok(Self::EnchantedHit),
            26 => Ok(Self::Enchant),
            27 => Ok(Self::EndRod),
            28 => Ok(Self::EntityEffect {
                color: Argb::from_bits(reader.i32()?),
            }),
            29 => Ok(Self::ExplosionEmitter),
            30 => Ok(Self::Explosion),
            31 => Ok(Self::Gust),
            32 => Ok(Self::SmallGust),
            33 => Ok(Self::GustEmitterLarge),
            34 => Ok(Self::GustEmitterSmall),
            35 => Ok(Self::SonicBoom),
            36 => Ok(Self::FallingDust {
                state: BlockStateId::from_raw(reader.var_int()?)?,
            }),
            37 => Ok(Self::Firework),
            38 => Ok(Self::Fishing),
            39 => Ok(Self::Flame),
            40 => Ok(Self::Infested),
            41 => Ok(Self::CherryLeaves),
            42 => Ok(Self::PaleOakLeaves),
            43 => Ok(Self::TintedLeaves {
                color: Argb::from_bits(reader.i32()?),
            }),
            44 => Ok(Self::SculkSoul),
            45 => Ok(Self::SculkCharge {
                roll: reader.f32()?,
            }),
            46 => Ok(Self::SculkChargePop),
            47 => Ok(Self::SoulFireFlame),
            48 => Ok(Self::Soul),
            49 => Ok(Self::Flash {
                color: Argb::from_bits(reader.i32()?),
            }),
            50 => Ok(Self::HappyVillager),
            51 => Ok(Self::Composter),
            52 => Ok(Self::Heart),
            53 => Ok(Self::InstantEffect {
                color: Argb::from_bits(reader.i32()?),
                power: reader.f32()?,
            }),
            54 => Ok(Self::Item {
                item_stack: ItemStackTemplate::decode(reader, nbt)?,
            }),
            55 => Ok(Self::Vibration {
                destination: PositionSource::decode(reader)?,
                arrival_in_ticks: reader.var_int()?,
            }),
            56 => Ok(Self::Trail {
                target: Vec3::decode(reader)?,
                color: Argb::from_bits(reader.i32()?),
                duration: reader.var_int()?,
            }),
            57 => Ok(Self::PauseMobGrowth),
            58 => Ok(Self::ResetMobGrowth),
            59 => Ok(Self::ItemSlime),
            60 => Ok(Self::ItemCobweb),
            61 => Ok(Self::ItemSnowball),
            62 => Ok(Self::LargeSmoke),
            63 => Ok(Self::Lava),
            64 => Ok(Self::Mycelium),
            65 => Ok(Self::Note),
            66 => Ok(Self::Poof),
            67 => Ok(Self::Portal),
            68 => Ok(Self::Rain),
            69 => Ok(Self::Smoke),
            70 => Ok(Self::WhiteSmoke),
            71 => Ok(Self::Sneeze),
            72 => Ok(Self::Spit),
            73 => Ok(Self::SquidInk),
            74 => Ok(Self::SweepAttack),
            75 => Ok(Self::TotemOfUndying),
            76 => Ok(Self::Underwater),
            77 => Ok(Self::Splash),
            78 => Ok(Self::Witch),
            79 => Ok(Self::BubblePop),
            80 => Ok(Self::CurrentDown),
            81 => Ok(Self::BubbleColumnUp),
            82 => Ok(Self::Nautilus),
            83 => Ok(Self::Dolphin),
            84 => Ok(Self::CampfireCosySmoke),
            85 => Ok(Self::CampfireSignalSmoke),
            86 => Ok(Self::DrippingHoney),
            87 => Ok(Self::FallingHoney),
            88 => Ok(Self::LandingHoney),
            89 => Ok(Self::FallingNectar),
            90 => Ok(Self::FallingSporeBlossom),
            91 => Ok(Self::Ash),
            92 => Ok(Self::CrimsonSpore),
            93 => Ok(Self::WarpedSpore),
            94 => Ok(Self::SporeBlossomAir),
            95 => Ok(Self::DrippingObsidianTear),
            96 => Ok(Self::FallingObsidianTear),
            97 => Ok(Self::LandingObsidianTear),
            98 => Ok(Self::ReversePortal),
            99 => Ok(Self::WhiteAsh),
            100 => Ok(Self::SmallFlame),
            101 => Ok(Self::Snowflake),
            102 => Ok(Self::DrippingDripstoneLava),
            103 => Ok(Self::FallingDripstoneLava),
            104 => Ok(Self::DrippingDripstoneWater),
            105 => Ok(Self::FallingDripstoneWater),
            106 => Ok(Self::GlowSquidInk),
            107 => Ok(Self::Glow),
            108 => Ok(Self::WaxOn),
            109 => Ok(Self::WaxOff),
            110 => Ok(Self::ElectricSpark),
            111 => Ok(Self::Scrape),
            112 => Ok(Self::Shriek {
                delay: reader.var_int()?,
            }),
            113 => Ok(Self::EggCrack),
            114 => Ok(Self::DustPlume),
            115 => Ok(Self::TrialSpawnerDetection),
            116 => Ok(Self::TrialSpawnerDetectionOminous),
            117 => Ok(Self::VaultConnection),
            118 => Ok(Self::DustPillar {
                state: BlockStateId::from_raw(reader.var_int()?)?,
            }),
            119 => Ok(Self::OminousSpawning),
            120 => Ok(Self::RaidOmen),
            121 => Ok(Self::TrialOmen),
            122 => Ok(Self::BlockCrumble {
                state: BlockStateId::from_raw(reader.var_int()?)?,
            }),
            123 => Ok(Self::Firefly),
            124 => Ok(Self::SulfurCubeGoo),
            value => Err(Error::InvalidEnum {
                name: "Particle",
                value,
            }),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{PARTICLE_NAMES, Particle, ParticleKind};
    use crate::generated::registry::PARTICLE_TYPE;

    /// The reason this table may live apart from `generated/registry.rs`.
    ///
    /// Two spellings of one registry can drift, and a particle id that has
    /// drifted draws the wrong particle rather than failing, so nothing would
    /// report it. This is what makes the split safe.
    #[test]
    fn particle_ids_match_the_registry() {
        for kind in ParticleKind::ALL {
            assert_eq!(
                PARTICLE_TYPE.id_of(kind.name()),
                Some(kind.id() as usize),
                "{} is id {} here",
                kind.name(),
                kind.id(),
            );
        }
    }

    /// A truncated table would compile and silently lack whatever Mojang added
    /// last, which is the end of the registry and so the highest ids.
    #[test]
    fn every_registry_entry_has_a_variant() {
        assert_eq!(ParticleKind::ALL.len(), PARTICLE_TYPE.entries.len());
        assert_eq!(PARTICLE_NAMES.len(), PARTICLE_TYPE.entries.len());
    }

    #[test]
    fn kind_round_trips_through_its_id_and_name() {
        for kind in ParticleKind::ALL {
            assert_eq!(ParticleKind::from_id(kind.id()), Some(*kind));
            assert_eq!(ParticleKind::from_name(kind.name()), Some(*kind));
        }
        assert_eq!(ParticleKind::from_id(125), None);
        assert_eq!(ParticleKind::from_name("minecraft:not_a_particle"), None);
    }

    /// The payload enum and the id-only enum have to agree, or a caller that
    /// matched on one and sent the other would send a different particle.
    #[test]
    fn a_body_less_particle_and_its_kind_share_an_id() {
        assert_eq!(Particle::Flame.kind(), ParticleKind::Flame);
        assert_eq!(Particle::Flame.id(), ParticleKind::Flame.id());
        assert_eq!(Particle::Flame.name(), ParticleKind::Flame.name());
    }
}
