[package]
name = "mobs"
version = { workspace = true }
edition = "2024"

[dependencies]
bevy_ecs = { workspace = true }
bevy_math = { workspace = true }
pathfinding = { path = "../pathfinding" }
temper-components = { workspace = true }
temper-entities = { workspace = true }
temper-messages = { workspace = true }
temper-state = { workspace = true }
temper-core = { workspace = true }
temper-particles = { workspace = true }
temper-utils = { workspace = true }
temper-resources = { workspace = true }
temper-text = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
