use heck::{ToShoutySnakeCase, ToSnakeCase};
use proc_macro2::Ident;
use quote::quote;
use std::fs;
use std::path::Path;
use syn::{Item, parse_file};

fn main() {
    println!("cargo::rerun-if-changed=src/markers.rs");
    println!("cargo::rerun-if-changed=build.rs");
    let src_path = "src/markers.rs";

    let content = fs::read_to_string(src_path).expect("Failed to read source file");

    let ast: syn::File = parse_file(&content).expect("Failed to parse Rust source file");

    let target_module_name = "entity_types";

    let mut enum_variants = Vec::new();
    let mut id_match_arms = Vec::new();
    let mut from_snake_match_arms = Vec::new();

    for item in ast.items {
        if let Item::Mod(module) = &item
            && module.ident == target_module_name
            && let Some((_, items)) = &module.content
        {
            for item in items {
                if let Item::Struct(struct_item) = item {
                    let ident = &struct_item.ident;
                    enum_variants.push(quote! { #ident });
                    let caps = Ident::new(
                        &ident.to_string().to_shouty_snake_case(),
                        proc_macro2::Span::call_site(),
                    );
                    id_match_arms.push(quote! {
                    Self::#ident => temper_data::generated::entities::EntityType::#caps,
                    });
                    let snake_str = ident.to_string().to_snake_case();
                    from_snake_match_arms.push(quote! {
                        #snake_str => Some(Self::#ident),
                    });
                }
            }
        }
    }

    let enum_name = Ident::new("EntityTypeEnum", proc_macro2::Span::call_site());
    let enum_def = quote! {
        #[derive(Eq, PartialEq, serde::Serialize, serde::Deserialize, Debug, Clone, Copy, Hash,)]
        pub enum #enum_name {
            #( #enum_variants ),*
        }

        impl #enum_name {
            pub fn to_entity_type(&self) -> temper_data::generated::entities::EntityType {
                match self {
                    #( #id_match_arms )*
                }
            }

            pub fn from_snake_case(name: &str) -> Option<Self> {
                match name {
                    #( #from_snake_match_arms )*
                    _ => None,
                }
            }
        }
    };

    let output_path = Path::new("src/entity_types.rs");
    fs::create_dir_all(output_path.parent().unwrap())
        .expect("Failed to create directory for generated enum");

    fs::write(output_path, format!("// @generated\n// This file is automatically generated from the list of markers in src/markers.rs\n{}", enum_def)).expect("Failed to write generated enum to file");
}
