// Passive entity bundles - entities that never attack players
pub mod allay;
pub mod armadillo;
pub mod axolotl;
pub mod bat;
pub mod camel;
pub mod cat;
pub mod chicken;
pub mod cod;
pub mod cow;
pub mod donkey;
pub mod frog;
pub mod glow_squid;
pub mod horse;
pub mod mooshroom;
pub mod mule;
pub mod ocelot;
pub mod parrot;
pub mod pig;
pub mod rabbit;
pub mod salmon;
pub mod sheep;
pub mod skeleton_horse;
pub mod sniffer;
pub mod snow_golem;
pub mod squid;
pub mod strider;
pub mod tadpole;
pub mod tropical_fish;
pub mod turtle;
pub mod villager;
pub mod wandering_trader;
pub mod zombie_horse;

// Re-exports
pub use allay::{AllayBundle, AllayDefinition};
pub use armadillo::{ArmadilloBundle, ArmadilloDefinition};
pub use axolotl::{AxolotlBundle, AxolotlDefinition};
pub use bat::{BatBundle, BatDefinition};
pub use camel::{CamelBundle, CamelDefinition};
pub use cat::{CatBundle, CatDefinition};
pub use chicken::{ChickenBundle, ChickenDefinition};
pub use cod::{CodBundle, CodDefinition};
pub use cow::{CowBundle, CowDefinition};
pub use donkey::{DonkeyBundle, DonkeyDefinition};
pub use frog::{FrogBundle, FrogDefinition};
pub use glow_squid::{GlowSquidBundle, GlowSquidDefinition};
pub use horse::{HorseBundle, HorseDefinition};
pub use mooshroom::{MooshroomBundle, MooshroomDefinition};
pub use mule::{MuleBundle, MuleDefinition};
pub use ocelot::{OcelotBundle, OcelotDefinition};
pub use parrot::{ParrotBundle, ParrotDefinition};
pub use pig::{PigBundle, PigDefinition};
pub use rabbit::{RabbitBundle, RabbitDefinition};
pub use salmon::{SalmonBundle, SalmonDefinition};
pub use sheep::{SheepBundle, SheepDefinition};
pub use skeleton_horse::{SkeletonHorseBundle, SkeletonHorseDefinition};
pub use sniffer::{SnifferBundle, SnifferDefinition};
pub use snow_golem::{SnowGolemBundle, SnowGolemDefinition};
pub use squid::{SquidBundle, SquidDefinition};
pub use strider::{StriderBundle, StriderDefinition};
pub use tadpole::{TadpoleBundle, TadpoleDefinition};
pub use tropical_fish::{TropicalFishBundle, TropicalFishDefinition};
pub use turtle::{TurtleBundle, TurtleDefinition};
pub use villager::{VillagerBundle, VillagerDefinition};
pub use wandering_trader::{WanderingTraderBundle, WanderingTraderDefinition};
pub use zombie_horse::{ZombieHorseBundle, ZombieHorseDefinition};
