// @generated by nix/generate-tag-data.py from Minecraft 26.2.
// Do not edit by hand. Regenerate with: nix run .#sync-minecraft-tag-data

//! Every tag a client is told about during configuration.
//!
//! A client loads tags from its own data packs, but it keeps them only until
//! the server speaks: handling `update_tags` replaces the whole map. A server
//! that sends an empty one therefore leaves the client with no tags at all,
//! and the next registry element naming a tag fails to parse -- which fails
//! the whole registry load, which fails `finish_configuration` and
//! disconnects with "Network Protocol Error". Sending these bytes is not an
//! optimisation; it is what makes a join work.
//!
//! # All of them, not the ones something happens to reference
//!
//! This is the full map `TagNetworkSerialization.serializeTagsToNetwork`
//! produces, which is what vanilla sends:
//! 697 tags across 15 registries, 35203 bytes of body.
//!
//! Trimming it to the tags today's registry elements name would be smaller,
//! and would break the first time a version bump or a data pack adds a
//! reference, with this module's own failure mode as the result.
//!
//! # Ids, not names
//!
//! A tag holds network ids, so these bytes are correct only for a server that
//! sends `registry_data` in the element order [`crate::registry_data`]
//! carries. Both come from one iteration of the server's own
//! `MappedRegistry`, which is by id.
//!
//! The one departure from the server's own bytes is that registries and tag
//! names are sorted. Vanilla builds both maps as a `HashMap`, so its order
//! changes from run to run; a map is unordered on the wire, so a client reads
//! the same tags either way.

use crate::{Encode, Error, Result, Writer};

/// Every registry with at least one tag, sorted by name.
///
/// `serializeTagsToNetwork` drops the empty payloads, so a registry absent
/// from here has no tags rather than unknown ones.
pub static ALL: &[&RegistryTagSet] = &[
    &BANNER_PATTERN,
    &BLOCK,
    &DAMAGE_TYPE,
    &DIALOG,
    &ENCHANTMENT,
    &ENTITY_TYPE,
    &FLUID,
    &GAME_EVENT,
    &INSTRUMENT,
    &ITEM,
    &PAINTING_VARIANT,
    &POINT_OF_INTEREST_TYPE,
    &POTION,
    &TIMELINE,
    &WORLDGEN_BIOME,
];

/// Byte length of the `minecraft:update_tags` body [`VanillaTags`] writes.
///
/// Committed rather than computed so that a change in the dump shows up as a
/// diff here, and so a test can hold the encoder to it.
pub const ENCODED_LEN: usize = 35203;

/// The tags of one registry (`TagNetworkSerialization.NetworkPayload`).
#[derive(Debug, Clone, Copy)]
pub struct RegistryTagSet {
    /// Registry the ids index into, e.g. `minecraft:block`.
    pub registry: &'static str,
    /// Tag names without the `#`, sorted.
    pub names: &'static [&'static str],
    /// Byte length of each tag's encoded id list, parallel to
    /// [`names`](Self::names).
    pub lengths: &'static [u32],
    /// Each tag's `VarInt` element count followed by its `VarInt` ids,
    /// concatenated in the same order.
    pub payloads: &'static [u8],
}

impl RegistryTagSet {
    /// Number of tags.
    #[must_use]
    pub const fn len(&self) -> usize {
        self.names.len()
    }

    /// True when the registry has no tags, which none of these do.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.names.is_empty()
    }

    /// Walk the tags as `(name, encoded id list)`.
    pub fn iter(&self) -> impl Iterator<Item = (&'static str, &'static [u8])> + '_ {
        let mut offset = 0usize;
        self.names
            .iter()
            .zip(self.lengths)
            .map(move |(name, length)| {
                let length = *length as usize;
                let payload = &self.payloads[offset..offset + length];
                offset += length;
                (*name, payload)
            })
    }

    /// Look up one tag's encoded id list by name.
    #[must_use]
    pub fn get(&self, name: &str) -> Option<&'static [u8]> {
        self.iter()
            .find_map(|(tag, payload)| (tag == name).then_some(payload))
    }

    /// Write this registry's entry in an `update_tags` body.
    ///
    /// # Errors
    /// Returns [`Error::NegativeLength`] only for a tag count a `VarInt`
    /// cannot describe, which no vanilla registry approaches.
    pub fn encode(&self, writer: &mut Writer) -> Result<()> {
        writer.string(self.registry)?;
        writer.var_int(i32::try_from(self.len()).map_err(|_| Error::NegativeLength(-1))?);
        for (name, payload) in self.iter() {
            writer.string(name)?;
            // `FriendlyByteBuf.writeIntIdList` bytes, element count included.
            writer.raw(payload);
        }
        Ok(())
    }
}

/// Find a registry's tags by name.
#[must_use]
pub fn by_name(name: &str) -> Option<&'static RegistryTagSet> {
    ALL.iter().copied().find(|set| set.registry == name)
}

/// The whole map, as the body of a `minecraft:update_tags` packet.
///
/// A type of its own rather than
/// [`crate::packets::configuration::UpdateTags`] because the ids are already
/// encoded in rodata: writing this is 697 memcpys, where filling in the
/// packet struct would build 697 `Vec`s on every join.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct VanillaTags;

impl Encode for VanillaTags {
    fn encode(&self, writer: &mut Writer) -> Result<()> {
        writer.var_int(i32::try_from(ALL.len()).map_err(|_| Error::NegativeLength(-1))?);
        for set in ALL {
            set.encode(writer)?;
        }
        Ok(())
    }
}

/// `minecraft:banner_pattern` (11 tags over 42 ids, 53 bytes).
pub static BANNER_PATTERN: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:banner_pattern",
    names: &[
        "minecraft:no_item_required",
        "minecraft:pattern_item/bordure_indented",
        "minecraft:pattern_item/creeper",
        "minecraft:pattern_item/field_masoned",
        "minecraft:pattern_item/flow",
        "minecraft:pattern_item/flower",
        "minecraft:pattern_item/globe",
        "minecraft:pattern_item/guster",
        "minecraft:pattern_item/mojang",
        "minecraft:pattern_item/piglin",
        "minecraft:pattern_item/skull",
    ],
    lengths: &[33, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    payloads: include_bytes!("minecraft.banner_pattern.bin"),
};

/// `minecraft:block` (265 tags over 4126 ids, 7637 bytes).
pub static BLOCK: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:block",
    names: &[
        "minecraft:acacia_logs",
        "minecraft:air",
        "minecraft:all_hanging_signs",
        "minecraft:all_signs",
        "minecraft:ancient_city_replaceable",
        "minecraft:animals_spawnable_on",
        "minecraft:anvil",
        "minecraft:armadillo_spawnable_on",
        "minecraft:axolotls_spawnable_on",
        "minecraft:azalea_grows_on",
        "minecraft:azalea_root_replaceable",
        "minecraft:badlands_terracotta",
        "minecraft:bamboo_blocks",
        "minecraft:banners",
        "minecraft:bars",
        "minecraft:base_stone_nether",
        "minecraft:base_stone_overworld",
        "minecraft:bats_spawnable_on",
        "minecraft:beacon_base_blocks",
        "minecraft:beds",
        "minecraft:bee_attractive",
        "minecraft:bee_growables",
        "minecraft:beehives",
        "minecraft:beneath_bamboo_podzol_replaceable",
        "minecraft:beneath_tree_podzol_replaceable",
        "minecraft:birch_logs",
        "minecraft:blocks_wind_charge_explosions",
        "minecraft:buttons",
        "minecraft:camel_sand_step_sound_blocks",
        "minecraft:camels_spawnable_on",
        "minecraft:campfires",
        "minecraft:can_glide_through",
        "minecraft:candle_cakes",
        "minecraft:candles",
        "minecraft:cannot_replace_below_tree_trunk",
        "minecraft:cannot_support_kelp",
        "minecraft:cannot_support_seagrass",
        "minecraft:cannot_support_snow_layer",
        "minecraft:cauldrons",
        "minecraft:causes_continuous_geyser_eruptions",
        "minecraft:causes_periodic_geyser_eruptions",
        "minecraft:cave_vines",
        "minecraft:ceiling_hanging_signs",
        "minecraft:chains",
        "minecraft:cherry_logs",
        "minecraft:climbable",
        "minecraft:coal_ores",
        "minecraft:combination_step_sound_blocks",
        "minecraft:completes_find_tree_tutorial",
        "minecraft:concrete",
        "minecraft:concrete_powders",
        "minecraft:convertable_to_mud",
        "minecraft:copper",
        "minecraft:copper_chests",
        "minecraft:copper_golem_statues",
        "minecraft:copper_ores",
        "minecraft:coral_blocks",
        "minecraft:coral_plants",
        "minecraft:corals",
        "minecraft:crimson_stems",
        "minecraft:crops",
        "minecraft:crystal_sound_blocks",
        "minecraft:dampens_vibrations",
        "minecraft:dark_oak_logs",
        "minecraft:deepslate_ore_replaceables",
        "minecraft:default_immune_to",
        "minecraft:diamond_ores",
        "minecraft:dirt",
        "minecraft:does_not_block_hoppers",
        "minecraft:doors",
        "minecraft:dragon_immune",
        "minecraft:dragon_transparent",
        "minecraft:dripstone_replaceable_blocks",
        "minecraft:edible_for_sheep",
        "minecraft:emerald_ores",
        "minecraft:enables_bubble_column_drag_down",
        "minecraft:enables_bubble_column_push_up",
        "minecraft:enchantment_power_provider",
        "minecraft:enchantment_power_transmitter",
        "minecraft:enderman_holdable",
        "minecraft:fall_damage_resetting",
        "minecraft:features_cannot_replace",
        "minecraft:fence_gates",
        "minecraft:fences",
        "minecraft:fire",
        "minecraft:flower_pots",
        "minecraft:flowers",
        "minecraft:forest_rock_can_place_on",
        "minecraft:fox_immune_to",
        "minecraft:foxes_spawnable_on",
        "minecraft:frog_prefer_jump_to",
        "minecraft:frogs_spawnable_on",
        "minecraft:geode_invalid_blocks",
        "minecraft:glazed_terracotta",
        "minecraft:goats_spawnable_on",
        "minecraft:gold_ores",
        "minecraft:grass_blocks",
        "minecraft:grows_crops",
        "minecraft:guarded_by_piglins",
        "minecraft:happy_ghast_avoids",
        "minecraft:hoglin_repellents",
        "minecraft:huge_brown_mushroom_can_place_on",
        "minecraft:huge_red_mushroom_can_place_on",
        "minecraft:ice",
        "minecraft:ice_spike_replaceable",
        "minecraft:impermeable",
        "minecraft:incorrect_for_copper_tool",
        "minecraft:incorrect_for_diamond_tool",
        "minecraft:incorrect_for_gold_tool",
        "minecraft:incorrect_for_iron_tool",
        "minecraft:incorrect_for_netherite_tool",
        "minecraft:incorrect_for_stone_tool",
        "minecraft:incorrect_for_wooden_tool",
        "minecraft:infiniburn_end",
        "minecraft:infiniburn_nether",
        "minecraft:infiniburn_overworld",
        "minecraft:inside_step_sound_blocks",
        "minecraft:invalid_spawn_inside",
        "minecraft:iron_ores",
        "minecraft:jungle_logs",
        "minecraft:lanterns",
        "minecraft:lapis_ores",
        "minecraft:lava_pool_stone_cannot_replace",
        "minecraft:leaves",
        "minecraft:lightning_rods",
        "minecraft:logs",
        "minecraft:logs_that_burn",
        "minecraft:lush_ground_replaceable",
        "minecraft:maintains_farmland",
        "minecraft:mangrove_logs",
        "minecraft:mangrove_logs_can_grow_through",
        "minecraft:mangrove_roots_can_grow_through",
        "minecraft:mineable/axe",
        "minecraft:mineable/hoe",
        "minecraft:mineable/pickaxe",
        "minecraft:mineable/shovel",
        "minecraft:mob_interactable_doors",
        "minecraft:mooshrooms_spawnable_on",
        "minecraft:moss_blocks",
        "minecraft:moss_replaceable",
        "minecraft:mud",
        "minecraft:needs_diamond_tool",
        "minecraft:needs_iron_tool",
        "minecraft:needs_stone_tool",
        "minecraft:nether_carver_replaceables",
        "minecraft:nylium",
        "minecraft:oak_logs",
        "minecraft:occludes_vibration_signals",
        "minecraft:overrides_mushroom_light_requirement",
        "minecraft:overworld_carver_replaceables",
        "minecraft:overworld_natural_logs",
        "minecraft:pale_oak_logs",
        "minecraft:parrots_spawnable_on",
        "minecraft:piglin_repellents",
        "minecraft:planks",
        "minecraft:polar_bear_immune_to",
        "minecraft:polar_bears_spawnable_on_alternate",
        "minecraft:portals",
        "minecraft:pressure_plates",
        "minecraft:prevent_mob_spawning_inside",
        "minecraft:prevents_nearby_leaf_decay",
        "minecraft:rabbits_spawnable_on",
        "minecraft:rails",
        "minecraft:redstone_ores",
        "minecraft:replaceable",
        "minecraft:replaceable_by_mushrooms",
        "minecraft:replaceable_by_trees",
        "minecraft:sand",
        "minecraft:saplings",
        "minecraft:sculk_replaceable",
        "minecraft:sculk_replaceable_world_gen",
        "minecraft:shears_extreme_breaking_speed",
        "minecraft:shears_major_breaking_speed",
        "minecraft:shears_minor_breaking_speed",
        "minecraft:shulker_boxes",
        "minecraft:signs",
        "minecraft:slabs",
        "minecraft:small_flowers",
        "minecraft:smelts_to_glass",
        "minecraft:snaps_goat_horn",
        "minecraft:sniffer_diggable_block",
        "minecraft:sniffer_egg_hatch_boost",
        "minecraft:snow",
        "minecraft:snow_golem_immune_to",
        "minecraft:soul_fire_base_blocks",
        "minecraft:soul_speed_blocks",
        "minecraft:speleothems",
        "minecraft:spruce_logs",
        "minecraft:stairs",
        "minecraft:standing_signs",
        "minecraft:stone_bricks",
        "minecraft:stone_buttons",
        "minecraft:stone_ore_replaceables",
        "minecraft:stone_pressure_plates",
        "minecraft:stray_immune_to",
        "minecraft:strider_warm_blocks",
        "minecraft:substrate_overworld",
        "minecraft:sulfur_spike_replaceable_blocks",
        "minecraft:support_override_cactus_flower",
        "minecraft:support_override_snow_layer",
        "minecraft:supports_azalea",
        "minecraft:supports_bamboo",
        "minecraft:supports_big_dripleaf",
        "minecraft:supports_cactus",
        "minecraft:supports_chorus_flower",
        "minecraft:supports_chorus_plant",
        "minecraft:supports_cocoa",
        "minecraft:supports_crimson_fungus",
        "minecraft:supports_crimson_roots",
        "minecraft:supports_crops",
        "minecraft:supports_dry_vegetation",
        "minecraft:supports_frogspawn",
        "minecraft:supports_hanging_mangrove_propagule",
        "minecraft:supports_lily_pad",
        "minecraft:supports_mangrove_propagule",
        "minecraft:supports_melon_stem",
        "minecraft:supports_melon_stem_fruit",
        "minecraft:supports_nether_sprouts",
        "minecraft:supports_nether_wart",
        "minecraft:supports_pumpkin_stem",
        "minecraft:supports_pumpkin_stem_fruit",
        "minecraft:supports_small_dripleaf",
        "minecraft:supports_stem_crops",
        "minecraft:supports_stem_fruit",
        "minecraft:supports_sugar_cane",
        "minecraft:supports_sugar_cane_adjacently",
        "minecraft:supports_vegetation",
        "minecraft:supports_warped_fungus",
        "minecraft:supports_warped_roots",
        "minecraft:supports_wither_rose",
        "minecraft:suppresses_bounce",
        "minecraft:sword_efficient",
        "minecraft:sword_instantly_mines",
        "minecraft:terracotta",
        "minecraft:trail_ruins_replaceable",
        "minecraft:trapdoors",
        "minecraft:triggers_ambient_desert_dry_vegetation_block_sounds",
        "minecraft:triggers_ambient_desert_sand_block_sounds",
        "minecraft:triggers_ambient_dried_ghast_block_sounds",
        "minecraft:underwater_bonemeals",
        "minecraft:unstable_bottom_center",
        "minecraft:valid_spawn",
        "minecraft:vibration_resonators",
        "minecraft:wall_corals",
        "minecraft:wall_hanging_signs",
        "minecraft:wall_post_override",
        "minecraft:wall_signs",
        "minecraft:walls",
        "minecraft:warped_stems",
        "minecraft:wart_blocks",
        "minecraft:wither_immune",
        "minecraft:wither_immune_to",
        "minecraft:wither_skeleton_immune_to",
        "minecraft:wither_summon_base_blocks",
        "minecraft:wolves_spawnable_on",
        "minecraft:wooden_buttons",
        "minecraft:wooden_doors",
        "minecraft:wooden_fences",
        "minecraft:wooden_pressure_plates",
        "minecraft:wooden_shelves",
        "minecraft:wooden_slabs",
        "minecraft:wooden_stairs",
        "minecraft:wooden_trapdoors",
        "minecraft:wool",
        "minecraft:wool_carpets",
    ],
    lengths: &[
        5, 6, 49, 97, 25, 2, 7, 18, 3, 57, 67, 15, 3, 65, 19, 7, 9, 9, 11, 17, 56, 23, 5, 16, 16,
        5, 4, 29, 36, 4, 5, 15, 35, 35, 13, 3, 3, 7, 9, 2, 3, 5, 25, 19, 5, 19, 3, 47, 68, 33, 33,
        5, 17, 17, 17, 5, 11, 11, 21, 9, 17, 5, 65, 5, 5, 1, 5, 5, 5, 43, 38, 7, 9, 9, 5, 3, 3, 3,
        56, 83, 23, 14, 25, 27, 5, 79, 60, 24, 3, 8, 5, 6, 10, 33, 10, 4, 5, 3, 68, 15, 9, 20, 20,
        9, 20, 38, 33, 1, 210, 11, 1, 33, 210, 6, 5, 5, 17, 5, 3, 5, 21, 3, 77, 12, 17, 53, 37, 32,
        49, 5, 12, 12, 523, 46, 998, 63, 41, 3, 5, 28, 4, 11, 23, 178, 42, 5, 5, 33, 8, 93, 10, 5,
        66, 11, 15, 3, 3, 7, 33, 7, 53, 7, 7, 5, 56, 103, 95, 4, 14, 92, 104, 12, 33, 5, 35, 49,
        137, 35, 3, 19, 14, 3, 7, 3, 5, 5, 5, 5, 129, 25, 9, 5, 5, 5, 3, 2, 16, 5, 5, 7, 20, 25,
        18, 4, 3, 3, 5, 24, 24, 3, 55, 1, 2, 5, 20, 3, 18, 24, 3, 3, 18, 5, 3, 18, 19, 3, 18, 24,
        24, 24, 3, 34, 5, 35, 2, 43, 37, 3, 5, 33, 25, 3, 3, 11, 25, 157, 25, 65, 9, 5, 30, 3, 3,
        5, 8, 25, 25, 25, 25, 25, 25, 25, 25, 33, 33,
    ],
    payloads: include_bytes!("minecraft.block.bin"),
};

/// `minecraft:damage_type` (34 tags over 229 ids, 263 bytes).
pub static DAMAGE_TYPE: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:damage_type",
    names: &[
        "minecraft:always_hurts_ender_dragons",
        "minecraft:always_kills_armor_stands",
        "minecraft:always_most_significant_fall",
        "minecraft:always_triggers_silverfish",
        "minecraft:avoids_guardian_thorns",
        "minecraft:burn_from_stepping",
        "minecraft:burns_armor_stands",
        "minecraft:bypasses_armor",
        "minecraft:bypasses_effects",
        "minecraft:bypasses_enchantments",
        "minecraft:bypasses_invulnerability",
        "minecraft:bypasses_resistance",
        "minecraft:bypasses_shield",
        "minecraft:bypasses_wolf_armor",
        "minecraft:can_break_armor_stand",
        "minecraft:damages_helmet",
        "minecraft:ignites_armor_stands",
        "minecraft:is_drowning",
        "minecraft:is_explosion",
        "minecraft:is_fall",
        "minecraft:is_fire",
        "minecraft:is_freezing",
        "minecraft:is_lightning",
        "minecraft:is_player_attack",
        "minecraft:is_projectile",
        "minecraft:mace_smash",
        "minecraft:no_anger",
        "minecraft:no_impact",
        "minecraft:no_knockback",
        "minecraft:panic_causes",
        "minecraft:panic_environmental_causes",
        "minecraft:sulfur_cube_with_block_immune_to",
        "minecraft:witch_resistant_to",
        "minecraft:wither_immune_to",
    ],
    lengths: &[
        5, 6, 2, 2, 7, 4, 2, 20, 2, 2, 3, 3, 31, 14, 5, 4, 3, 2, 5, 4, 9, 2, 2, 4, 9, 2, 2, 2, 31,
        30, 9, 28, 5, 2,
    ],
    payloads: include_bytes!("minecraft.damage_type.bin"),
};

/// `minecraft:dialog` (2 tags over 0 ids, 2 bytes).
pub static DIALOG: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:dialog",
    names: &[
        "minecraft:pause_screen_additions",
        "minecraft:quick_actions",
    ],
    lengths: &[1, 1],
    payloads: include_bytes!("minecraft.dialog.bin"),
};

/// `minecraft:enchantment` (22 tags over 308 ids, 330 bytes).
pub static ENCHANTMENT: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:enchantment",
    names: &[
        "minecraft:curse",
        "minecraft:double_trade_price",
        "minecraft:exclusive_set/armor",
        "minecraft:exclusive_set/boots",
        "minecraft:exclusive_set/bow",
        "minecraft:exclusive_set/crossbow",
        "minecraft:exclusive_set/damage",
        "minecraft:exclusive_set/mining",
        "minecraft:exclusive_set/riptide",
        "minecraft:in_enchanting_table",
        "minecraft:non_treasure",
        "minecraft:on_mob_spawn_equipment",
        "minecraft:on_random_loot",
        "minecraft:on_traded_equipment",
        "minecraft:prevents_bee_spawns_when_mining",
        "minecraft:prevents_decorated_pot_shattering",
        "minecraft:prevents_ice_melting",
        "minecraft:prevents_infested_spawns",
        "minecraft:smelts_loot",
        "minecraft:tooltip_order",
        "minecraft:tradeable",
        "minecraft:treasure",
    ],
    lengths: &[
        3, 8, 5, 3, 3, 3, 7, 3, 3, 37, 37, 37, 41, 37, 2, 2, 2, 2, 2, 44, 41, 8,
    ],
    payloads: include_bytes!("minecraft.enchantment.bin"),
};

/// `minecraft:entity_type` (48 tags over 375 ids, 544 bytes).
pub static ENTITY_TYPE: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:entity_type",
    names: &[
        "minecraft:accepts_iron_golem_gift",
        "minecraft:aquatic",
        "minecraft:arrows",
        "minecraft:arthropod",
        "minecraft:axolotl_always_hostiles",
        "minecraft:axolotl_hunt_targets",
        "minecraft:beehive_inhabitors",
        "minecraft:boat",
        "minecraft:burn_in_daylight",
        "minecraft:can_breathe_under_water",
        "minecraft:can_equip_harness",
        "minecraft:can_equip_saddle",
        "minecraft:can_float_while_ridden",
        "minecraft:can_turn_in_boats",
        "minecraft:can_wear_horse_armor",
        "minecraft:can_wear_nautilus_armor",
        "minecraft:candidate_for_iron_golem_gift",
        "minecraft:cannot_be_age_locked",
        "minecraft:cannot_be_pushed_onto_boats",
        "minecraft:deflects_projectiles",
        "minecraft:dismounts_underwater",
        "minecraft:fall_damage_immune",
        "minecraft:followable_friendly_mobs",
        "minecraft:freeze_hurts_extra_types",
        "minecraft:freeze_immune_entity_types",
        "minecraft:frog_food",
        "minecraft:ignores_poison_and_regen",
        "minecraft:illager",
        "minecraft:illager_friends",
        "minecraft:immune_to_infested",
        "minecraft:immune_to_oozing",
        "minecraft:impact_projectiles",
        "minecraft:inverted_healing_and_harm",
        "minecraft:nautilus_hostiles",
        "minecraft:no_anger_from_wind_charge",
        "minecraft:non_controlling_rider",
        "minecraft:not_affected_by_geysers",
        "minecraft:not_scary_for_pufferfish",
        "minecraft:powder_snow_walkable_mobs",
        "minecraft:raiders",
        "minecraft:redirectable_projectile",
        "minecraft:sensitive_to_bane_of_arthropods",
        "minecraft:sensitive_to_impaling",
        "minecraft:sensitive_to_smite",
        "minecraft:skeletons",
        "minecraft:undead",
        "minecraft:wither_friends",
        "minecraft:zombies",
    ],
    lengths: &[
        2, 19, 3, 6, 4, 10, 2, 11, 17, 45, 2, 15, 8, 2, 4, 4, 4, 6, 20, 2, 17, 20, 29, 5, 7, 3, 27,
        6, 6, 2, 2, 16, 27, 2, 12, 5, 2, 20, 5, 9, 5, 6, 19, 27, 9, 27, 27, 16,
    ],
    payloads: include_bytes!("minecraft.entity_type.bin"),
};

/// `minecraft:fluid` (6 tags over 9 ids, 15 bytes).
pub static FLUID: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:fluid",
    names: &[
        "minecraft:bubble_column_can_occupy",
        "minecraft:lava",
        "minecraft:supports_frogspawn",
        "minecraft:supports_lily_pad",
        "minecraft:supports_sugar_cane_adjacently",
        "minecraft:water",
    ],
    lengths: &[2, 3, 2, 2, 3, 3],
    payloads: include_bytes!("minecraft.fluid.bin"),
};

/// `minecraft:game_event` (5 tags over 121 ids, 126 bytes).
pub static GAME_EVENT: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:game_event",
    names: &[
        "minecraft:allay_can_listen",
        "minecraft:ignore_vibrations_sneaking",
        "minecraft:shrieker_can_listen",
        "minecraft:vibrations",
        "minecraft:warden_can_listen",
    ],
    lengths: &[2, 7, 2, 57, 58],
    payloads: include_bytes!("minecraft.game_event.bin"),
};

/// `minecraft:instrument` (3 tags over 16 ids, 19 bytes).
pub static INSTRUMENT: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:instrument",
    names: &[
        "minecraft:goat_horns",
        "minecraft:regular_goat_horns",
        "minecraft:screaming_goat_horns",
    ],
    lengths: &[9, 5, 5],
    payloads: include_bytes!("minecraft.instrument.bin"),
};

/// `minecraft:item` (224 tags over 2712 ids, 5377 bytes).
pub static ITEM: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:item",
    names: &[
        "minecraft:acacia_logs",
        "minecraft:anvil",
        "minecraft:armadillo_food",
        "minecraft:arrows",
        "minecraft:axes",
        "minecraft:axolotl_food",
        "minecraft:bamboo_blocks",
        "minecraft:banners",
        "minecraft:bars",
        "minecraft:beacon_payment_items",
        "minecraft:beds",
        "minecraft:bee_food",
        "minecraft:birch_logs",
        "minecraft:boats",
        "minecraft:book_cloning_target",
        "minecraft:bookshelf_books",
        "minecraft:breaks_decorated_pots",
        "minecraft:brewing_fuel",
        "minecraft:bundles",
        "minecraft:buttons",
        "minecraft:camel_food",
        "minecraft:camel_husk_food",
        "minecraft:candles",
        "minecraft:cat_collar_dyes",
        "minecraft:cat_food",
        "minecraft:cauldron_can_remove_dye",
        "minecraft:chains",
        "minecraft:cherry_logs",
        "minecraft:chest_armor",
        "minecraft:chest_boats",
        "minecraft:chicken_food",
        "minecraft:cluster_max_harvestables",
        "minecraft:coal_ores",
        "minecraft:coals",
        "minecraft:compasses",
        "minecraft:completes_find_tree_tutorial",
        "minecraft:concrete",
        "minecraft:concrete_powders",
        "minecraft:copper",
        "minecraft:copper_chests",
        "minecraft:copper_golem_statues",
        "minecraft:copper_ores",
        "minecraft:copper_tool_materials",
        "minecraft:cow_food",
        "minecraft:creeper_drop_music_discs",
        "minecraft:creeper_igniters",
        "minecraft:crimson_stems",
        "minecraft:dampens_vibrations",
        "minecraft:dark_oak_logs",
        "minecraft:decorated_pot_ingredients",
        "minecraft:decorated_pot_sherds",
        "minecraft:diamond_ores",
        "minecraft:diamond_tool_materials",
        "minecraft:dirt",
        "minecraft:doors",
        "minecraft:drowned_preferred_weapons",
        "minecraft:duplicates_allays",
        "minecraft:dyes",
        "minecraft:eggs",
        "minecraft:emerald_ores",
        "minecraft:enchantable/armor",
        "minecraft:enchantable/bow",
        "minecraft:enchantable/chest_armor",
        "minecraft:enchantable/crossbow",
        "minecraft:enchantable/durability",
        "minecraft:enchantable/equippable",
        "minecraft:enchantable/fire_aspect",
        "minecraft:enchantable/fishing",
        "minecraft:enchantable/foot_armor",
        "minecraft:enchantable/head_armor",
        "minecraft:enchantable/leg_armor",
        "minecraft:enchantable/lunge",
        "minecraft:enchantable/mace",
        "minecraft:enchantable/melee_weapon",
        "minecraft:enchantable/mining",
        "minecraft:enchantable/mining_loot",
        "minecraft:enchantable/sharp_weapon",
        "minecraft:enchantable/sweeping",
        "minecraft:enchantable/trident",
        "minecraft:enchantable/vanishing",
        "minecraft:enchantable/weapon",
        "minecraft:fence_gates",
        "minecraft:fences",
        "minecraft:fishes",
        "minecraft:flowers",
        "minecraft:foot_armor",
        "minecraft:fox_food",
        "minecraft:freeze_immune_wearables",
        "minecraft:frog_food",
        "minecraft:furnace_minecart_fuel",
        "minecraft:gaze_disguise_equipment",
        "minecraft:glazed_terracotta",
        "minecraft:goat_food",
        "minecraft:gold_ores",
        "minecraft:gold_tool_materials",
        "minecraft:grass_blocks",
        "minecraft:hanging_signs",
        "minecraft:happy_ghast_food",
        "minecraft:happy_ghast_tempt_items",
        "minecraft:harnesses",
        "minecraft:head_armor",
        "minecraft:hoes",
        "minecraft:hoglin_food",
        "minecraft:horse_food",
        "minecraft:horse_tempt_items",
        "minecraft:ignored_by_piglin_babies",
        "minecraft:iron_ores",
        "minecraft:iron_tool_materials",
        "minecraft:jungle_logs",
        "minecraft:lanterns",
        "minecraft:lapis_ores",
        "minecraft:leaves",
        "minecraft:lectern_books",
        "minecraft:leg_armor",
        "minecraft:lightning_rods",
        "minecraft:llama_food",
        "minecraft:llama_tempt_items",
        "minecraft:logs",
        "minecraft:logs_that_burn",
        "minecraft:loom_dyes",
        "minecraft:loom_patterns",
        "minecraft:mangrove_logs",
        "minecraft:map_invisibility_equipment",
        "minecraft:meat",
        "minecraft:metal_nuggets",
        "minecraft:moss_blocks",
        "minecraft:mud",
        "minecraft:nautilus_bucket_food",
        "minecraft:nautilus_food",
        "minecraft:nautilus_taming_items",
        "minecraft:netherite_tool_materials",
        "minecraft:non_flammable_wood",
        "minecraft:noteblock_top_instruments",
        "minecraft:oak_logs",
        "minecraft:ocelot_food",
        "minecraft:pale_oak_logs",
        "minecraft:panda_eats_from_ground",
        "minecraft:panda_food",
        "minecraft:parrot_food",
        "minecraft:parrot_poisonous_food",
        "minecraft:pickaxes",
        "minecraft:pig_food",
        "minecraft:piglin_food",
        "minecraft:piglin_loved",
        "minecraft:piglin_preferred_weapons",
        "minecraft:piglin_repellents",
        "minecraft:piglin_safe_armor",
        "minecraft:pillager_preferred_weapons",
        "minecraft:planks",
        "minecraft:rabbit_food",
        "minecraft:rails",
        "minecraft:redstone_ores",
        "minecraft:repairs_chain_armor",
        "minecraft:repairs_copper_armor",
        "minecraft:repairs_diamond_armor",
        "minecraft:repairs_gold_armor",
        "minecraft:repairs_iron_armor",
        "minecraft:repairs_leather_armor",
        "minecraft:repairs_netherite_armor",
        "minecraft:repairs_turtle_helmet",
        "minecraft:repairs_wolf_armor",
        "minecraft:sand",
        "minecraft:saplings",
        "minecraft:shearable_from_copper_golem",
        "minecraft:sheep_food",
        "minecraft:shovels",
        "minecraft:shulker_boxes",
        "minecraft:signs",
        "minecraft:skeleton_preferred_weapons",
        "minecraft:skulls",
        "minecraft:slabs",
        "minecraft:small_flowers",
        "minecraft:smelts_to_glass",
        "minecraft:sniffer_food",
        "minecraft:soul_fire_base_blocks",
        "minecraft:spears",
        "minecraft:spruce_logs",
        "minecraft:stairs",
        "minecraft:stone_bricks",
        "minecraft:stone_buttons",
        "minecraft:stone_crafting_materials",
        "minecraft:stone_tool_materials",
        "minecraft:strider_food",
        "minecraft:strider_tempt_items",
        "minecraft:sulfur_cube_archetype/bouncy",
        "minecraft:sulfur_cube_archetype/explosive",
        "minecraft:sulfur_cube_archetype/fast_flat",
        "minecraft:sulfur_cube_archetype/fast_sliding",
        "minecraft:sulfur_cube_archetype/high_resistance",
        "minecraft:sulfur_cube_archetype/hot",
        "minecraft:sulfur_cube_archetype/light",
        "minecraft:sulfur_cube_archetype/regular",
        "minecraft:sulfur_cube_archetype/slow_bouncy",
        "minecraft:sulfur_cube_archetype/slow_flat",
        "minecraft:sulfur_cube_archetype/slow_sliding",
        "minecraft:sulfur_cube_archetype/sticky",
        "minecraft:sulfur_cube_food",
        "minecraft:sulfur_cube_swallowable",
        "minecraft:swords",
        "minecraft:terracotta",
        "minecraft:trapdoors",
        "minecraft:trim_materials",
        "minecraft:trimmable_armor",
        "minecraft:turtle_food",
        "minecraft:villager_picks_up",
        "minecraft:villager_plantable_seeds",
        "minecraft:walls",
        "minecraft:warped_stems",
        "minecraft:wart_blocks",
        "minecraft:wither_skeleton_disliked_weapons",
        "minecraft:wolf_collar_dyes",
        "minecraft:wolf_food",
        "minecraft:wooden_buttons",
        "minecraft:wooden_doors",
        "minecraft:wooden_fences",
        "minecraft:wooden_pressure_plates",
        "minecraft:wooden_shelves",
        "minecraft:wooden_slabs",
        "minecraft:wooden_stairs",
        "minecraft:wooden_tool_materials",
        "minecraft:wooden_trapdoors",
        "minecraft:wool",
        "minecraft:wool_carpets",
        "minecraft:zombie_horse_food",
    ],
    lengths: &[
        9, 7, 3, 7, 15, 3, 5, 33, 19, 11, 33, 58, 9, 41, 3, 11, 75, 3, 35, 29, 3, 3, 35, 33, 5, 13,
        19, 9, 15, 21, 13, 15, 3, 5, 5, 115, 33, 33, 9, 17, 17, 3, 3, 3, 25, 5, 9, 65, 9, 49, 47,
        3, 3, 4, 43, 3, 3, 33, 7, 3, 59, 3, 15, 3, 167, 77, 31, 3, 15, 17, 15, 15, 3, 29, 59, 57,
        43, 15, 3, 185, 45, 25, 27, 13, 62, 15, 5, 11, 3, 5, 3, 33, 3, 4, 3, 5, 25, 3, 35, 33, 17,
        15, 3, 17, 7, 3, 3, 3, 9, 21, 3, 23, 5, 15, 17, 5, 3, 89, 73, 33, 21, 9, 3, 23, 7, 5, 4, 9,
        21, 5, 3, 63, 15, 9, 5, 9, 5, 3, 13, 3, 15, 7, 5, 52, 5, 7, 9, 3, 13, 7, 9, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 4, 14, 3, 3, 15, 35, 25, 3, 15, 128, 35, 3, 3, 5, 15, 9, 120, 9, 5, 5, 5, 3,
        5, 106, 3, 53, 7, 5, 3, 33, 48, 251, 72, 15, 3, 3, 588, 15, 35, 43, 23, 59, 3, 19, 13, 56,
        9, 5, 5, 33, 37, 25, 25, 25, 25, 25, 25, 25, 13, 25, 33, 33, 3,
    ],
    payloads: include_bytes!("minecraft.item.bin"),
};

/// `minecraft:painting_variant` (1 tags over 47 ids, 48 bytes).
pub static PAINTING_VARIANT: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:painting_variant",
    names: &["minecraft:placeable"],
    lengths: &[48],
    payloads: include_bytes!("minecraft.painting_variant.bin"),
};

/// `minecraft:point_of_interest_type` (3 tags over 30 ids, 33 bytes).
pub static POINT_OF_INTEREST_TYPE: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:point_of_interest_type",
    names: &[
        "minecraft:acquirable_job_site",
        "minecraft:bee_home",
        "minecraft:village",
    ],
    lengths: &[14, 3, 16],
    payloads: include_bytes!("minecraft.point_of_interest_type.bin"),
};

/// `minecraft:potion` (1 tags over 41 ids, 42 bytes).
pub static POTION: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:potion",
    names: &["minecraft:tradeable"],
    lengths: &[42],
    payloads: include_bytes!("minecraft.potion.bin"),
};

/// `minecraft:timeline` (4 tags over 7 ids, 11 bytes).
pub static TIMELINE: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:timeline",
    names: &[
        "minecraft:in_end",
        "minecraft:in_nether",
        "minecraft:in_overworld",
        "minecraft:universal",
    ],
    lengths: &[2, 2, 5, 2],
    payloads: include_bytes!("minecraft.timeline.bin"),
};

/// `minecraft:worldgen/biome` (68 tags over 581 ids, 649 bytes).
pub static WORLDGEN_BIOME: RegistryTagSet = RegistryTagSet {
    registry: "minecraft:worldgen/biome",
    names: &[
        "minecraft:allows_surface_slime_spawns",
        "minecraft:allows_tropical_fish_spawns_at_any_height",
        "minecraft:has_structure/ancient_city",
        "minecraft:has_structure/bastion_remnant",
        "minecraft:has_structure/buried_treasure",
        "minecraft:has_structure/desert_pyramid",
        "minecraft:has_structure/end_city",
        "minecraft:has_structure/igloo",
        "minecraft:has_structure/jungle_temple",
        "minecraft:has_structure/mineshaft",
        "minecraft:has_structure/mineshaft_mesa",
        "minecraft:has_structure/nether_fortress",
        "minecraft:has_structure/nether_fossil",
        "minecraft:has_structure/ocean_monument",
        "minecraft:has_structure/ocean_ruin_cold",
        "minecraft:has_structure/ocean_ruin_warm",
        "minecraft:has_structure/pillager_outpost",
        "minecraft:has_structure/ruined_portal_desert",
        "minecraft:has_structure/ruined_portal_jungle",
        "minecraft:has_structure/ruined_portal_mountain",
        "minecraft:has_structure/ruined_portal_nether",
        "minecraft:has_structure/ruined_portal_ocean",
        "minecraft:has_structure/ruined_portal_standard",
        "minecraft:has_structure/ruined_portal_swamp",
        "minecraft:has_structure/shipwreck",
        "minecraft:has_structure/shipwreck_beached",
        "minecraft:has_structure/stronghold",
        "minecraft:has_structure/swamp_hut",
        "minecraft:has_structure/trail_ruins",
        "minecraft:has_structure/trial_chambers",
        "minecraft:has_structure/village_desert",
        "minecraft:has_structure/village_plains",
        "minecraft:has_structure/village_savanna",
        "minecraft:has_structure/village_snowy",
        "minecraft:has_structure/village_taiga",
        "minecraft:has_structure/woodland_mansion",
        "minecraft:is_badlands",
        "minecraft:is_beach",
        "minecraft:is_deep_ocean",
        "minecraft:is_end",
        "minecraft:is_forest",
        "minecraft:is_hill",
        "minecraft:is_jungle",
        "minecraft:is_mountain",
        "minecraft:is_nether",
        "minecraft:is_ocean",
        "minecraft:is_overworld",
        "minecraft:is_river",
        "minecraft:is_savanna",
        "minecraft:is_taiga",
        "minecraft:mineshaft_blocking",
        "minecraft:more_frequent_drowned_spawns",
        "minecraft:polar_bears_spawn_on_alternate_blocks",
        "minecraft:produces_corals_from_bonemeal",
        "minecraft:reduce_water_ambient_spawns",
        "minecraft:required_ocean_monument_surrounding",
        "minecraft:spawns_cold_variant_farm_animals",
        "minecraft:spawns_cold_variant_frogs",
        "minecraft:spawns_coral_variant_zombie_nautilus",
        "minecraft:spawns_gold_rabbits",
        "minecraft:spawns_snow_foxes",
        "minecraft:spawns_warm_variant_farm_animals",
        "minecraft:spawns_warm_variant_frogs",
        "minecraft:spawns_white_rabbits",
        "minecraft:stronghold_biased_to",
        "minecraft:water_on_map_outlines",
        "minecraft:without_wandering_trader_spawns",
        "minecraft:without_zombie_sieges",
    ],
    lengths: &[
        3, 2, 2, 5, 3, 2, 3, 4, 3, 52, 4, 6, 2, 5, 7, 4, 13, 2, 4, 16, 6, 10, 25, 3, 10, 3, 56, 2,
        7, 55, 2, 3, 2, 2, 2, 3, 4, 3, 5, 6, 8, 4, 4, 7, 6, 10, 56, 3, 4, 5, 2, 3, 3, 2, 3, 12, 27,
        18, 2, 2, 11, 20, 18, 11, 39, 14, 2, 2,
    ],
    payloads: include_bytes!("minecraft.worldgen.biome.bin"),
};
