[package]
edition.workspace = true
license.workspace = true
name = "hyperion-hot-reload-demo"
publish = false
repository.workspace = true
version.workspace = true

[[bin]]
name = "hot-reload-demo"
path = "src/main.rs"

[dependencies]
flecs_ecs.workspace = true
hyperion-hot-reload.workspace = true

[lints]
workspace = true
